// ---------------------------------------------------------------------------
// Bridge: Tauri progress events  →  operationsStore
//
// Single source of truth that listens for the various long-running events
// emitted from the backend and routes them into the operations overlay.
// Mounted once from AppShell on app start.
// ---------------------------------------------------------------------------

import { setupTauriListeners } from '$lib/utils/tauri-listeners';
import { operationsStore, type OperationStep } from '$lib/stores/operations.svelte';
import { workspacesStore } from '$lib/stores/workspaces.svelte';
import type { StepStatus } from '$lib/components/shared/ui/ProgressStepper.svelte';
import type {
  WorkspaceFetchProgressEvent,
  WorkspacePullProgressEvent,
  WorkspacePullDoneEvent,
} from '$lib/types/workspace';

// ---------------------------------------------------------------------------
// Pull (single repo) — events emitted from `pull_branch` backend command.
// op_id is generated by the IPC wrapper before invoking the command.
// ---------------------------------------------------------------------------

/** Phase keys defined by the pull backend (kept in sync with `PullPrepPhase`). */
export const PULL_PHASE_KEYS = ['status', 'stash', 'fetch', 'merge', 'unstash'] as const;
export type PullPhase = typeof PULL_PHASE_KEYS[number];

interface PullProgressEvent {
  op_id:  string;
  phase:  PullPhase;
  label:  string;
  detail?: string | null;
  /** Optional non-fatal note (e.g. "no stash needed — workdir clean").
   *  Backend uses this to mark a phase as `skipped` while keeping its
   *  card row visible. */
  skipped?: boolean;
}

// Default phase ordering + labels used when the frontend pre-creates the
// operation (so steps render before the first event arrives).  Mirrors the
// labels emitted by the backend.
export const PULL_DEFAULT_STEPS: OperationStep[] = [
  { key: 'status',   label: 'Checking workdir' },
  { key: 'stash',    label: 'Stashing local changes' },
  { key: 'fetch',    label: 'Fetching from origin' },
  { key: 'merge',    label: 'Merging / fast-forward' },
  { key: 'unstash',  label: 'Restoring stash' },
];

// ---------------------------------------------------------------------------
// Linked-worktree sync — orchestrator-driven (no user-side IPC wrapper).
// We create the op when `-started` arrives.
// ---------------------------------------------------------------------------

interface LinkSyncStarted {
  link_id:           string;
  link_name:         string;
  initiator_repo_id: string;
  target_branch:     string;
}

interface LinkSyncProgress {
  link_id:    string;
  repo_id:    string;
  /** Resolved member display name when the registry knows it; falls back
   *  to repo_id otherwise. */
  repo_name?: string | null;
  /** Branch each member was asked to switch to (may differ from initiator
   *  via the alias map). */
  target_branch: string;
  index:      number;
  total:      number;
  /** 'start' | 'ok' | 'skipped' | 'error' | 'conflict' */
  phase:      string;
  /** Human-readable detail / error message for the phase. */
  detail?:    string | null;
}

interface LinkSyncDoneSummary {
  link_id:           string;
  link_name:         string;
  target_branch:     string;
  initiator_repo_id: string;
  results: Array<{
    repo_id: string;
    status: { kind: string; [k: string]: unknown };
  }>;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function repoLabel(repoId: string): string {
  const entry = workspacesStore.registryById.get(repoId);
  return entry?.display_name ?? repoId;
}

function workspaceLabel(wsId: string): string {
  return workspacesStore.workspaces.find(w => w.id === wsId)?.name ?? 'Workspace';
}

function workspaceRepoSteps(wsId: string): OperationStep[] {
  // Build the step list from the workspace membership at the time of
  // kick-off.  Order matches the backend's iteration (registry order).
  const ws = workspacesStore.workspaces.find(w => w.id === wsId);
  if (!ws) return [];
  return ws.repo_ids
    .map(id => workspacesStore.registryById.get(id))
    .filter((e): e is NonNullable<typeof e> => !!e)
    .filter(e => !!e.path) // backend filters missing paths too
    .map(e => ({ key: e.id, label: e.display_name }));
}

function mapWorkspacePhase(phase: string): StepStatus {
  switch (phase) {
    case 'start':    return 'active';
    case 'ok':       return 'completed';
    case 'error':    return 'error';
    case 'conflict': return 'error';
    case 'skipped':  return 'skipped';
    default:         return 'pending';
  }
}

function mapLinkSyncPhase(phase: string): StepStatus {
  switch (phase) {
    case 'start':    return 'active';
    case 'ok':       return 'completed';
    case 'error':    return 'error';
    case 'conflict': return 'error';
    case 'skipped':  return 'skipped';
    default:         return 'pending';
  }
}

// ---------------------------------------------------------------------------
// Public: pre-create operations BEFORE invoking the backend.
// Called by the per-action wrappers (pullBranch, workspaceFetchAll, …).
// ---------------------------------------------------------------------------

export function startPullOperation(
  opId: string,
  repoLabelText: string,
  branchLabel?: string | null,
): void {
  operationsStore.start({
    id:       opId,
    title:    `Pull ${branchLabel ?? ''}`.trim() || 'Pull',
    subtitle: repoLabelText,
    steps:    PULL_DEFAULT_STEPS,
    current:  'status',
  });
}

export function startWorkspaceFetchOperation(jobId: string, wsId: string): void {
  const steps = workspaceRepoSteps(wsId);
  operationsStore.start({
    id:       jobId,
    title:    `Fetch ${workspaceLabel(wsId)}`,
    subtitle: `${steps.length} repos`,
    steps,
    current:  steps[0]?.key ?? null,
  });
}

export function startWorkspacePullOperation(jobId: string, wsId: string): void {
  const steps = workspaceRepoSteps(wsId);
  operationsStore.start({
    id:       jobId,
    title:    `Pull ${workspaceLabel(wsId)}`,
    subtitle: `${steps.length} repos`,
    steps,
    current:  steps[0]?.key ?? null,
  });
}

// ---------------------------------------------------------------------------
// Listener bootstrap — call once on app start, returns cleanup.
// ---------------------------------------------------------------------------

export function setupOperationBridge(): () => void {
  return setupTauriListeners([
    // ── Pull (single repo) ───────────────────────────────────────────────
    {
      event: 'arbor://pull-progress',
      handler: (e: { payload: PullProgressEvent }) => {
        const p = e.payload;
        if (p.skipped) {
          // Skipped phase: stamp a sticky 'skipped' override so the step
          // keeps its dashed-circle indicator after the op finishes.  Don't
          // move `current` — the next non-skipped phase event will.
          operationsStore.updateStep(p.op_id, p.phase, {
            status: 'skipped',
            detail: p.detail ?? null,
          });
        } else {
          // Active phase: only record detail; let the ProgressStepper's
          // position-based logic mark earlier phases as completed.  Writing
          // `status: 'active'` here would be sticky and leave the step
          // spinning forever after the op completes.
          operationsStore.updateStep(p.op_id, p.phase, {
            detail: p.detail ?? null,
          });
          operationsStore.update(p.op_id, {
            current:      p.phase,
            activeDetail: p.detail ?? null,
          });
        }
      },
    },
    {
      event: 'arbor://pull-done',
      handler: (e: { payload: { op_id: string; status: 'ok' | 'conflict' | 'error'; summary?: string | null; error?: string | null } }) => {
        const p = e.payload;
        operationsStore.finish(p.op_id, {
          summary: p.summary ?? null,
          error:   p.status === 'error' ? (p.error ?? 'Pull failed')
                 : p.status === 'conflict' ? (p.error ?? 'Stash apply produced conflicts')
                 : null,
        });
      },
    },

    // ── Workspace fetch-all ──────────────────────────────────────────────
    {
      event: 'arbor://workspace-fetch-progress',
      handler: (e: { payload: WorkspaceFetchProgressEvent }) => {
        const p = e.payload;
        const status = mapWorkspacePhase(p.phase);
        operationsStore.updateStep(p.job_id, p.repo_id, {
          status,
          detail: p.error ?? (status === 'completed' ? 'fetched' : null),
        });
        if (p.phase === 'start') {
          operationsStore.update(p.job_id, {
            current:      p.repo_id,
            activeDetail: repoLabel(p.repo_id),
          });
        }
      },
    },
    {
      event: 'arbor://workspace-fetch-done',
      handler: (e: { payload: { job_id: string; workspace_id: string; ok: number; failed: number } }) => {
        const p = e.payload;
        operationsStore.finish(p.job_id, {
          summary: `${p.ok} ok · ${p.failed} failed`,
          error:   p.failed > 0 ? `${p.failed} repo${p.failed === 1 ? '' : 's'} failed to fetch` : null,
        });
      },
    },

    // ── Workspace pull-all ───────────────────────────────────────────────
    {
      event: 'arbor://workspace-pull-progress',
      handler: (e: { payload: WorkspacePullProgressEvent }) => {
        const p = e.payload;
        const status = mapWorkspacePhase(p.phase);
        const detail = p.error
          ?? (status === 'completed' ? 'pulled'
            : status === 'error'     ? 'pull failed'
            : null);
        operationsStore.updateStep(p.job_id, p.repo_id, { status, detail });
        if (p.phase === 'start') {
          operationsStore.update(p.job_id, {
            current:      p.repo_id,
            activeDetail: repoLabel(p.repo_id),
          });
        }
      },
    },
    {
      event: 'arbor://workspace-pull-done',
      handler: (e: { payload: WorkspacePullDoneEvent }) => {
        const p = e.payload;
        const issues = p.failed + p.conflict;
        operationsStore.finish(p.job_id, {
          summary: `${p.ok} ok · ${p.conflict} conflict · ${p.failed} failed`,
          error:   issues > 0
            ? `${p.failed} failed${p.conflict > 0 ? `, ${p.conflict} with conflicts` : ''}`
            : null,
        });
      },
    },

    // ── Plugin-driven operations (arbor.ui.operation.*) ─────────────────
    // Lua plugins push to the same overlay used by Pull / Fetch-all so
    // long-running plugin work (release notes generation, source-export
    // compile, …) gets the same step-by-step progress card. The id is
    // pre-namespaced with the plugin name on the Rust side, so collisions
    // across plugins are impossible.
    {
      event: 'arbor://plugin-operation-start',
      handler: (e: { payload: {
        id:        string;
        plugin:    string;
        title:     string;
        subtitle?: string | null;
        steps:     OperationStep[];
        current?:  string | null;
      } }) => {
        const p = e.payload;
        operationsStore.start({
          id:       p.id,
          title:    p.title,
          subtitle: p.subtitle ?? p.plugin,
          steps:    p.steps ?? [],
          current:  p.current ?? p.steps?.[0]?.key ?? null,
        });
      },
    },
    {
      event: 'arbor://plugin-operation-update',
      handler: (e: { payload: {
        id:      string;
        plugin:  string;
        kind:    'set_current' | 'update_step';
        step:    string;
        status?: StepStatus | null;
        detail?: string | null;
      } }) => {
        const p = e.payload;
        if (p.kind === 'set_current') {
          // Move the active-step pointer; let the stepper compute
          // pending/completed positions from `current` so we don't have
          // to send sticky `status: 'active'` (which would freeze the
          // step as spinning forever after the op finishes).
          operationsStore.updateStep(p.id, p.step, {
            detail: p.detail ?? null,
          });
          operationsStore.update(p.id, {
            current:      p.step,
            activeDetail: p.detail ?? null,
          });
        } else {
          // Per-step patch: status overrides (skipped / error) + detail.
          const patch: Partial<OperationStep> = {};
          if (p.status !== undefined && p.status !== null) patch.status = p.status;
          if (p.detail !== undefined) patch.detail = p.detail ?? null;
          operationsStore.updateStep(p.id, p.step, patch);
        }
      },
    },
    {
      event: 'arbor://plugin-operation-finish',
      handler: (e: { payload: {
        id:       string;
        plugin:   string;
        summary?: string | null;
        error?:   string | null;
      } }) => {
        const p = e.payload;
        operationsStore.finish(p.id, {
          summary: p.summary ?? null,
          error:   p.error   ?? null,
        });
      },
    },

    // ── Linked-worktree sync ─────────────────────────────────────────────
    {
      event: 'arbor://worktree-link-sync-started',
      handler: (e: { payload: LinkSyncStarted }) => {
        const p = e.payload;
        // We don't yet know which non-initiator members will be processed
        // (the orchestrator computes them).  Render a placeholder card with
        // the initiator info; per-member events fill in real steps as they
        // arrive.  If for some reason no -progress event ever comes (the
        // orchestrator skips silently), the -done summary still finishes
        // the op.
        const initiatorName = repoLabel(p.initiator_repo_id);
        operationsStore.start({
          id:       `linkwt:${p.link_id}`,
          title:    `Sync ${p.link_name}`,
          subtitle: `→ ${p.target_branch} (from ${initiatorName})`,
          steps:    [],
          current:  null,
        });
      },
    },
    {
      event: 'arbor://worktree-link-sync-progress',
      handler: (e: { payload: LinkSyncProgress }) => {
        const p = e.payload;
        const opId   = `linkwt:${p.link_id}`;
        const stepKey = p.repo_id;
        const stepLabel = p.repo_name ?? repoLabel(p.repo_id);

        // First sighting of this repo within the op?  Append a step.
        const op = operationsStore.operations.find(o => o.id === opId);
        if (op && !op.steps.some(s => s.key === stepKey)) {
          operationsStore.update(opId, {
            steps: [
              ...op.steps,
              { key: stepKey, label: stepLabel, detail: p.target_branch },
            ],
          });
        }

        const status = mapLinkSyncPhase(p.phase);
        operationsStore.updateStep(opId, stepKey, {
          status,
          detail: p.detail ?? p.target_branch,
        });
        if (p.phase === 'start') {
          operationsStore.update(opId, {
            current:      stepKey,
            activeDetail: `${stepLabel} → ${p.target_branch}`,
          });
        }
      },
    },
    {
      event: 'arbor://worktree-link-sync-done',
      handler: (e: { payload: LinkSyncDoneSummary }) => {
        const p = e.payload;
        const opId = `linkwt:${p.link_id}`;
        const total   = p.results.length;
        // Lightweight count: results carry the tagged MemberStatus enum
        // (#[serde(tag = "kind")] in Rust), so the discriminator field is
        // `kind` — values: "updated", "skipped", "skipped_missing",
        // "conflict", "error".
        let ok = 0, fail = 0, skipped = 0;
        for (const r of p.results) {
          const k = r?.status?.kind ?? '';
          if      (k === 'updated')                       ok++;
          else if (k === 'error' || k === 'conflict')     fail++;
          else                                            skipped++;
        }
        operationsStore.finish(opId, {
          summary: total === 0
            ? 'No linked members to sync'
            : `${ok} updated · ${skipped} skipped · ${fail} failed`,
          error:   fail > 0 ? `${fail} member${fail === 1 ? '' : 's'} failed to sync` : null,
        });
      },
    },
  ]);
}
