/**
 * Library breakpoints: which buffers offer the margin, and how a view names its class.
 *
 * The decision worth pinning is the stub: a decompiled view's line numbers mean nothing to the VM,
 * so offering a breakpoint there would offer one that binds to an arbitrary statement.
 */

import { describe, expect, it } from 'vitest';
import {
  breakpointLanguageOf,
  isDecompiledStub,
  isLibraryBreakpointAt,
  libraryClassLabel,
  libraryClassOfSource,
  outerClass,
} from './library-breakpoints';

const VIEW = 'C:/Users/me/AppData/Roaming/arbor/bennu/decompiled/org/springframework/web/client/RestClient.java';

const REAL = `/*
 * Copyright 2002-2024 the original author or authors.
 * package not.this.one;
 */

package org.springframework.web.client;

import java.net.URI;

public interface RestClient {
}
`;

const STUB = `// Decompiled from bytecode — no source attached. Signatures only (method bodies
// are not present in a .class file). Generated by Bennu.

package org.springframework.web.client;

public interface RestClient {
}
`;

describe('libraryClassOfSource', () => {
  it('joins the package declaration and the file stem', () => {
    expect(libraryClassOfSource(VIEW, REAL)).toBe('org.springframework.web.client.RestClient');
  });

  it('ignores a package line inside the licence comment', () => {
    expect(libraryClassOfSource(VIEW, REAL)).not.toContain('not.this.one');
  });

  it('reads the default package as no package', () => {
    expect(libraryClassOfSource('C:\\data\\decompiled\\Main.java', 'public class Main {}')).toBe('Main');
  });

  it('refuses what is not a class compilation unit', () => {
    expect(libraryClassOfSource('C:/data/decompiled/org/acme/package-info.java', 'package org.acme;')).toBeNull();
    expect(libraryClassOfSource('C:/data/library/app/web.xml', '<web-app/>')).toBeNull();
  });
});

describe('breakpointLanguageOf', () => {
  it('offers project files by language', () => {
    expect(breakpointLanguageOf({ path: 'C:/p/src/Order.java', language: 'java', libraryView: false, source: '' })).toBe('java');
    expect(breakpointLanguageOf({ path: 'C:/p/src/main.rs', language: 'rust', libraryView: false, source: '' })).toBe('rust');
    expect(breakpointLanguageOf({ path: 'C:/p/app.properties', language: null, libraryView: false, source: '' })).toBeNull();
    expect(breakpointLanguageOf({ path: null, language: 'java', libraryView: false, source: '' })).toBeNull();
  });

  it('offers a library view holding real source', () => {
    expect(breakpointLanguageOf({ path: VIEW, language: 'java', libraryView: true, source: REAL })).toBe('java');
  });

  it('refuses a decompiled stub, whose line numbers mean nothing to the VM', () => {
    expect(isDecompiledStub(STUB)).toBe(true);
    expect(isDecompiledStub(REAL)).toBe(false);
    expect(breakpointLanguageOf({ path: VIEW, language: 'java', libraryView: true, source: STUB })).toBeNull();
  });

  it('refuses a library view that has not loaded yet', () => {
    expect(breakpointLanguageOf({ path: VIEW, language: 'java', libraryView: true, source: '' })).toBeNull();
  });
});

describe('matching a stop to a library breakpoint', () => {
  const bp = { class: 'org.springframework.web.client.RestClient', line: 118 };

  it('matches the class, or a class nested in it, on the same line', () => {
    expect(isLibraryBreakpointAt(bp, 'org.springframework.web.client.RestClient', 118)).toBe(true);
    expect(isLibraryBreakpointAt(bp, 'org.springframework.web.client.RestClient$Builder$1', 118)).toBe(true);
  });

  it('does not match another line, another class, or a project breakpoint', () => {
    expect(isLibraryBreakpointAt(bp, 'org.springframework.web.client.RestClient', 119)).toBe(false);
    expect(isLibraryBreakpointAt(bp, 'org.springframework.web.client.RestClientBuilder', 118)).toBe(false);
    expect(isLibraryBreakpointAt(bp, 'org.springframework.web.client.RestClient', null)).toBe(false);
    expect(isLibraryBreakpointAt({ line: 118 }, 'org.springframework.web.client.RestClient', 118)).toBe(false);
  });

  it('labels a class by simple name and package', () => {
    expect(outerClass('a.B$C')).toBe('a.B');
    expect(libraryClassLabel('org.springframework.web.client.RestClient$Builder')).toEqual({
      simple: 'RestClient',
      pkg: 'org.springframework.web.client',
    });
    expect(libraryClassLabel('Main')).toEqual({ simple: 'Main', pkg: '' });
  });
});
