<#
.SYNOPSIS
    Refreshes the javac golden files of the bennu-check differential corpus.

.DESCRIPTION
    1. Runs the system `mvn` (on the JDK that JAVA_HOME / PATH points at, JDK 21) with the `oracle`
       profile, which makes the forked javac write its raw transcript to <module>/target/javac-raw.txt.
    2. Extracts every located javac diagnostic into <module>/expected.txt, one per line:
           relative/path/File.java:LINE:COL: compiler.err.key
       paths relative to the module's src/main/java, sorted, de-duplicated, UTF-8 without BOM, LF.
    3. Cross-checks the inline `// error:` / `// warn:` markers against it and prints every
       disagreement as "CORPUS CASE IS WRONG": the markers are a human guess, javac is the truth.

    4. For the clean modules (clean8, clean21: realistic legal code, no markers) javac must report
       nothing: every diagnostic there is printed as "CLEAN MODULE DOES NOT COMPILE - corpus bug".

    Exit code 0 when every module was extracted and agrees with its markers and every clean module
    compiled silently, 1 otherwise.
    POSIX twin: refresh-expected.sh (the two produce byte-identical golden files).

.PARAMETER SkipMaven
    Re-extract from the previous run's output without running Maven again.
#>
[CmdletBinding()]
param([switch]$SkipMaven)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$Root = $PSScriptRoot
$Modules = @('java8', 'java21')
# Realistic legal code without markers: javac must report nothing on them.
$CleanModules = @('clean8', 'clean21')
$Utf8NoBom = New-Object System.Text.UTF8Encoding $false
$LogPath = Join-Path $Root 'target\mvn-refresh.log'
$GoldenHeader = '# javac oracle for this corpus module. Generated by refresh-expected.ps1 / refresh-expected.sh; do not edit.'

# `[ERROR] C:\...\File.java:[12,9] compiler.err.key: ...` - maven-compiler-plugin re-printing a diagnostic.
$MavenPattern = '^\[(?:ERROR|WARNING)\]\s+(?<file>.+?\.java):\[(?<line>\d+),(?<col>\d+)\]\s*(?<key>compiler\.(?:err|warn)\.[^:\s]+)'
# `File.java:12:9: compiler.err.key: ...` - javac -XDrawDiagnostics, as written to javac-raw.txt.
$RawPattern = '^(?<file>.+?\.java):(?<line>\d+):(?<col>\d+):\s*(?<key>compiler\.(?:err|warn)\.[^:\s]+)'

function Invoke-OracleBuild {
    if (-not (Get-Command mvn -ErrorAction SilentlyContinue)) {
        throw 'mvn is not on PATH. Install Maven and point JAVA_HOME at a JDK 21.'
    }
    Write-Host "Running: mvn -B -P oracle -fae clean compile   (in $Root)"
    Push-Location $Root
    $previous = $ErrorActionPreference
    # A native tool's stderr lines arrive as error records; they must not abort the script.
    $ErrorActionPreference = 'Continue'
    try {
        $output = & mvn -B -P oracle -fae clean compile 2>&1 | ForEach-Object { "$_" }
        $exitCode = $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $previous
        Pop-Location
    }
    New-Item -ItemType Directory -Force -Path (Split-Path $LogPath) | Out-Null
    [System.IO.File]::WriteAllLines($LogPath, [string[]]@($output), $Utf8NoBom)
    Write-Host "Maven exited with code $exitCode (compile errors are expected). Log: $LogPath"
}

function Get-SourceRoot([string]$Module) {
    return (Join-Path $Root "$Module\src\main\java")
}

function Get-RelativePath([string]$SourceRoot, [System.IO.FileInfo]$File) {
    return $File.FullName.Substring($SourceRoot.Length + 1).Replace('\', '/')
}

# File name -> relative paths, to attribute javac's bare `File.java` locators.
function Get-SourceIndex([string]$SourceRoot) {
    $byName = @{}
    foreach ($file in Get-ChildItem -Path $SourceRoot -Recurse -Filter '*.java' -File) {
        if (-not $byName.ContainsKey($file.Name)) {
            $byName[$file.Name] = New-Object System.Collections.Generic.List[string]
        }
        $byName[$file.Name].Add((Get-RelativePath $SourceRoot $file))
    }
    return $byName
}

function Resolve-CorpusPath([string]$Reported, [string]$Module, $Index, [bool]$AllowBareNames) {
    $normalized = $Reported.Replace('\', '/')
    $moduleRoot = "/$Module/src/main/java/"
    $at = $normalized.IndexOf($moduleRoot, [System.StringComparison]::OrdinalIgnoreCase)
    if ($at -ge 0) { return $normalized.Substring($at + $moduleRoot.Length) }
    if ($normalized.StartsWith('src/main/java/')) { return $normalized.Substring('src/main/java/'.Length) }
    if ($normalized.Contains('/')) { return $null }   # a path into the other module
    if (-not $AllowBareNames) { return $null }        # a bare name in the shared Maven log is unattributable
    if (-not $Index.ContainsKey($normalized)) {
        Write-Warning "[$Module] javac names $normalized, which is not a corpus source"
        return $null
    }
    $candidates = $Index[$normalized]
    if ($candidates.Count -gt 1) {
        Write-Warning "[$Module] file name $normalized is not unique in the module; its diagnostics are skipped"
        return $null
    }
    return $candidates[0]
}

# Every located diagnostic of the module as `rel:line:col: key`, sorted; $null when there is no input.
function Get-ModuleDiagnostics([string]$Module) {
    $sourceRoot = Get-SourceRoot $Module
    $index = Get-SourceIndex $sourceRoot
    $rawPath = Join-Path $Root "$Module\target\javac-raw.txt"
    if (Test-Path $rawPath) {
        $lines = [System.IO.File]::ReadAllLines($rawPath)
        $allowBareNames = $true
    } elseif (Test-Path $LogPath) {
        Write-Warning "[$Module] $rawPath is missing; falling back to the Maven log (full-path diagnostics only)."
        $lines = [System.IO.File]::ReadAllLines($LogPath)
        $allowBareNames = $false
    } else {
        Write-Warning "[$Module] no javac output found (neither $rawPath nor $LogPath)."
        return $null
    }

    $entries = @{}
    foreach ($line in $lines) {
        $match = [regex]::Match($line, $MavenPattern)
        if (-not $match.Success) { $match = [regex]::Match($line, $RawPattern) }
        if (-not $match.Success) { continue }
        $relative = Resolve-CorpusPath $match.Groups['file'].Value $Module $index $allowBareNames
        if ($null -eq $relative) { continue }
        $lineNumber = [int]$match.Groups['line'].Value
        $column = [int]$match.Groups['col'].Value
        $key = $match.Groups['key'].Value
        # Zero-padded so an ordinal sort orders numbers numerically, like `sort -k2,2n` in the .sh twin.
        $sortKey = '{0}|{1:D8}|{2:D8}|{3}' -f $relative, $lineNumber, $column, $key
        $entries[$sortKey] = '{0}:{1}:{2}: {3}' -f $relative, $lineNumber, $column, $key
    }
    $sortKeys = New-Object System.Collections.Generic.List[string]
    foreach ($sortKey in $entries.Keys) { $sortKeys.Add($sortKey) }
    $sortKeys.Sort([System.StringComparer]::Ordinal)
    $sorted = New-Object System.Collections.Generic.List[string]
    foreach ($sortKey in $sortKeys) { $sorted.Add($entries[$sortKey]) }
    return ,$sorted.ToArray()
}

# The author's expectations as `rel:line: key`.
function Get-Markers([string]$Module) {
    $sourceRoot = Get-SourceRoot $Module
    $markers = [System.Collections.Generic.SortedSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($file in Get-ChildItem -Path $sourceRoot -Recurse -Filter '*.java' -File) {
        $relative = Get-RelativePath $sourceRoot $file
        $number = 0
        foreach ($text in [System.IO.File]::ReadAllLines($file.FullName)) {
            $number++
            $at = $text.LastIndexOf('//')
            if ($at -lt 0) { continue }
            $match = [regex]::Match($text.Substring($at + 2).Trim(), '^(?:error|warn):\s*(?<keys>.+)$')
            if (-not $match.Success) { continue }
            foreach ($key in ($match.Groups['keys'].Value -split '[\s,]+')) {
                if ($key.StartsWith('compiler.')) { [void]$markers.Add(('{0}:{1}: {2}' -f $relative, $number, $key)) }
            }
        }
    }
    return ,$markers
}

function Write-Disagreements([string]$Module, [string]$Title, [string[]]$Rows) {
    if ($Rows.Count -eq 0) { return }
    Write-Host ""
    Write-Host "[$Module] CORPUS CASE IS WRONG - $Title ($($Rows.Count)):" -ForegroundColor Yellow
    foreach ($row in $Rows) { Write-Host "    $row" }
}

# Prints marker/javac disagreements and returns how many there were.
function Compare-Markers([string]$Module, [string[]]$Diagnostics, $Markers) {
    $reported = [System.Collections.Generic.SortedSet[string]]::new([System.StringComparer]::Ordinal)
    foreach ($diagnostic in $Diagnostics) {
        [void]$reported.Add(($diagnostic -replace '^([^:]+):(\d+):\d+: ', '$1:$2: '))
    }
    $unreported = @($Markers | Where-Object { -not $reported.Contains($_) })
    $unmarked = @($reported | Where-Object { -not $Markers.Contains($_) })
    Write-Disagreements $Module 'a marker expects a diagnostic javac did not report' $unreported
    Write-Disagreements $Module 'javac reports a diagnostic no marker announces' $unmarked
    return ($unreported.Count + $unmarked.Count)
}

function Write-Golden([string]$Module, [string[]]$Diagnostics) {
    $goldenPath = Join-Path $Root "$Module\expected.txt"
    $content = (@($GoldenHeader) + $Diagnostics) -join "`n"
    [System.IO.File]::WriteAllText($goldenPath, $content + "`n", $Utf8NoBom)
    Write-Host "[$Module] $($Diagnostics.Count) diagnostics -> $Module/expected.txt"
}

# A clean module must compile silently. Prints every javac diagnostic in it; returns the problem count.
function Test-CleanModule([string]$Module, [string[]]$Diagnostics) {
    $problems = 0
    $rawPath = Join-Path $Root "$Module\target\javac-raw.txt"
    $classesPath = Join-Path $Root "$Module\target\classes"
    $classes = @(Get-ChildItem -Path $classesPath -Recurse -Filter '*.class' -File -ErrorAction SilentlyContinue)
    if (-not (Test-Path $rawPath) -or $classes.Count -eq 0) {
        Write-Host ""
        Write-Host "[$Module] CLEAN MODULE NOT VERIFIED - no javac transcript or no compiled classes under $Module/target." -ForegroundColor Red
        $problems++
    }
    if ($Diagnostics.Count -gt 0) {
        Write-Host ""
        Write-Host "[$Module] CLEAN MODULE DOES NOT COMPILE - corpus bug ($($Diagnostics.Count) javac diagnostics):" -ForegroundColor Red
        foreach ($diagnostic in $Diagnostics) { Write-Host "    $diagnostic" }
        $problems += $Diagnostics.Count
    }
    return $problems
}

if (-not $SkipMaven) { Invoke-OracleBuild }

$problems = 0
foreach ($module in $Modules) {
    $diagnostics = Get-ModuleDiagnostics $module
    if ($null -eq $diagnostics) { $problems++; continue }
    $markers = Get-Markers $module
    if ($diagnostics.Count -eq 0 -and $markers.Count -gt 0) {
        Write-Warning "[$module] no diagnostics extracted although the sources carry markers; expected.txt left untouched."
        $problems++
        continue
    }
    Write-Golden $module $diagnostics
    $problems += Compare-Markers $module $diagnostics $markers
}

foreach ($module in $CleanModules) {
    $diagnostics = Get-ModuleDiagnostics $module
    if ($null -eq $diagnostics) { $problems++; continue }
    Write-Golden $module $diagnostics
    $problems += Test-CleanModule $module $diagnostics
}

Write-Host ""
if ($problems -gt 0) {
    Write-Host "$problems problem(s) - fix the corpus cases (or their markers) listed above." -ForegroundColor Yellow
    exit 1
}
Write-Host 'Every marker agrees with javac and every clean module compiles silently.' -ForegroundColor Green
exit 0
