#!/usr/bin/env bash
# Refreshes the javac golden files of the bennu-check differential corpus.
# POSIX twin of refresh-expected.ps1; both write byte-identical golden files.
#
#   ./refresh-expected.sh               run mvn (oracle profile), extract, cross-check markers
#   ./refresh-expected.sh --skip-maven  re-extract from the previous run's output
#
# 1. Runs the system `mvn` (on the JDK of JAVA_HOME / PATH, JDK 21) with the `oracle` profile, which
#    makes the forked javac write its raw transcript to <module>/target/javac-raw.txt.
# 2. Writes <module>/expected.txt: `relative/path/File.java:LINE:COL: compiler.err.key`, paths
#    relative to src/main/java, sorted, de-duplicated, UTF-8 without BOM, LF.
# 3. Prints every disagreement between the `// error:` / `// warn:` markers and javac as
#    "CORPUS CASE IS WRONG".
# 4. For the clean modules (clean8, clean21: realistic legal code, no markers) javac must report
#    nothing: every diagnostic there is printed as "CLEAN MODULE DOES NOT COMPILE - corpus bug".
# Exit code 1 when any step finds a problem.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULES=(java8 java21)
# Realistic legal code without markers: javac must report nothing on them.
CLEAN_MODULES=(clean8 clean21)
LOG="$ROOT/target/mvn-refresh.log"
HEADER='# javac oracle for this corpus module. Generated by refresh-expected.ps1 / refresh-expected.sh; do not edit.'
SKIP_MAVEN=0
if [ "${1:-}" = "--skip-maven" ]; then SKIP_MAVEN=1; fi

# Byte-order sorting and matching, identical to the ordinal sort of the PowerShell twin.
export LC_ALL=C
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

run_maven() {
  if ! command -v mvn >/dev/null 2>&1; then
    echo "mvn is not on PATH. Install Maven and point JAVA_HOME at a JDK 21." >&2
    exit 2
  fi
  echo "Running: mvn -B -P oracle -fae clean compile   (in $ROOT)"
  local code=0
  ( cd "$ROOT" && mvn -B -P oracle -fae clean compile ) > "$WORK/mvn.log" 2>&1 || code=$?
  mkdir -p "$ROOT/target"
  cp "$WORK/mvn.log" "$LOG"
  echo "Maven exited with code $code (compile errors are expected). Log: $LOG"
}

# `file|line|col|key` for every located diagnostic, in either shape:
#   [ERROR] C:\...\File.java:[12,9] compiler.err.key: ...   (maven-compiler-plugin re-printing)
#   File.java:12:9: compiler.err.key: ...                   (javac -XDrawDiagnostics)
normalize() {
  tr -d '\r' < "$1" | sed -E -n \
    -e 's/^\[(ERROR|WARNING)\][[:space:]]+(.+\.java):\[([0-9]+),([0-9]+)\][[:space:]]*(compiler\.(err|warn)\.[^:[:space:]]+).*$/\2|\3|\4|\5/p' \
    -e 't' \
    -e 's/^(.+\.java):([0-9]+):([0-9]+):[[:space:]]*(compiler\.(err|warn)\.[^:[:space:]]+).*$/\1|\2|\3|\4/p'
}

# The module's diagnostics as sorted `rel:line:col: key` lines on stdout; status 1 with no input.
extract_module() {
  local module="$1"
  local src="$ROOT/$module/src/main/java"
  local raw="$ROOT/$module/target/javac-raw.txt"
  local input allow_bare
  if [ -f "$raw" ]; then
    input="$raw"; allow_bare=1
  elif [ -f "$LOG" ]; then
    echo "warning: [$module] $raw is missing; falling back to the Maven log (full-path diagnostics only)." >&2
    input="$LOG"; allow_bare=0
  else
    echo "error: [$module] no javac output found (neither $raw nor $LOG)." >&2
    return 1
  fi
  ( cd "$src" && find . -name '*.java' -type f | sed 's|^\./||' ) > "$WORK/$module.index"
  normalize "$input" | awk -F'|' -v module="$module" -v allow_bare="$allow_bare" -v index_file="$WORK/$module.index" '
    BEGIN {
      while ((getline rel < index_file) > 0) {
        n = split(rel, parts, "/"); name = parts[n]; count[name]++; path[name] = rel
      }
      module_root = "/" module "/src/main/java/"
    }
    {
      file = $1
      gsub(/\\/, "/", file)
      at = index(file, module_root)
      if (at > 0) rel = substr(file, at + length(module_root))
      else if (index(file, "src/main/java/") == 1) rel = substr(file, 15)
      else if (index(file, "/") > 0) next
      else if (!allow_bare) next
      else if (count[file] == 1) rel = path[file]
      else if (count[file] > 1) { printf "warning: [%s] file name %s is not unique in the module; skipped\n", module, file > "/dev/stderr"; next }
      else { printf "warning: [%s] javac names %s, which is not a corpus source\n", module, file > "/dev/stderr"; next }
      printf "%s:%s:%s: %s\n", rel, $2, $3, $4
    }' | sort -t: -k1,1 -k2,2n -k3,3n -k4,4 -u
}

# The author's expectations as sorted `rel:line: key` lines.
markers_of() {
  local src="$ROOT/$1/src/main/java"
  { ( cd "$src" && grep -rnE --include='*.java' '//[[:space:]]*(error|warn):' . ) || true; } \
    | tr -d '\r' | sed 's|^\./||' | awk '
    {
      first = index($0, ":"); rel = substr($0, 1, first - 1); rest = substr($0, first + 1)
      second = index(rest, ":"); line = substr(rest, 1, second - 1); text = substr(rest, second + 1)
      sub(/.*\/\/[ \t]*(error|warn):/, "", text)
      n = split(text, keys, /[ \t,]+/)
      for (i = 1; i <= n; i++) if (keys[i] ~ /^compiler\./) printf "%s:%s: %s\n", rel, line, keys[i]
    }' | sort -u
}

print_rows() {
  local module="$1" title="$2" rows="$3"
  [ -n "$rows" ] || return 0
  echo
  echo "[$module] CORPUS CASE IS WRONG - $title ($(printf '%s\n' "$rows" | wc -l | tr -d ' ')):"
  printf '%s\n' "$rows" | sed 's/^/    /'
}

PROBLEMS=0

# Prints marker/javac disagreements of one module and adds them to PROBLEMS.
cross_check() {
  local module="$1" golden="$2"
  { grep -v '^#' "$golden" || true; } | sed -E 's/^([^:]+):([0-9]+):[0-9]+: /\1:\2: /' | sort -u > "$WORK/$module.reported"
  local unreported unmarked
  unreported="$(comm -23 "$WORK/$module.markers" "$WORK/$module.reported")"
  unmarked="$(comm -13 "$WORK/$module.markers" "$WORK/$module.reported")"
  print_rows "$module" "a marker expects a diagnostic javac did not report" "$unreported"
  print_rows "$module" "javac reports a diagnostic no marker announces" "$unmarked"
  if [ -n "$unreported" ]; then PROBLEMS=$((PROBLEMS + $(printf '%s\n' "$unreported" | wc -l))); fi
  if [ -n "$unmarked" ]; then PROBLEMS=$((PROBLEMS + $(printf '%s\n' "$unmarked" | wc -l))); fi
}

# Writes <module>/expected.txt from the extracted diagnostics.
write_golden() {
  local module="$1" count
  count="$(wc -l < "$WORK/$module.golden" | tr -d ' ')"
  { printf '%s\n' "$HEADER"; cat "$WORK/$module.golden"; } > "$ROOT/$module/expected.txt"
  echo "[$module] $count diagnostics -> $module/expected.txt"
}

# A clean module must compile silently: prints every javac diagnostic in it and adds them to PROBLEMS.
check_clean() {
  local module="$1" count first_class
  count="$(wc -l < "$WORK/$module.golden" | tr -d ' ')"
  first_class="$({ find "$ROOT/$module/target/classes" -name '*.class' -type f 2>/dev/null || true; } | head -n 1)"
  if [ ! -f "$ROOT/$module/target/javac-raw.txt" ] || [ -z "$first_class" ]; then
    echo
    echo "[$module] CLEAN MODULE NOT VERIFIED - no javac transcript or no compiled classes under $module/target."
    PROBLEMS=$((PROBLEMS + 1))
  fi
  if [ "$count" -gt 0 ]; then
    echo
    echo "[$module] CLEAN MODULE DOES NOT COMPILE - corpus bug ($count javac diagnostics):"
    sed 's/^/    /' "$WORK/$module.golden"
    PROBLEMS=$((PROBLEMS + count))
  fi
}

if [ "$SKIP_MAVEN" -eq 0 ]; then run_maven; fi

for module in "${MODULES[@]}"; do
  if ! extract_module "$module" > "$WORK/$module.golden"; then
    PROBLEMS=$((PROBLEMS + 1))
    continue
  fi
  markers_of "$module" > "$WORK/$module.markers"
  count="$(wc -l < "$WORK/$module.golden" | tr -d ' ')"
  if [ "$count" -eq 0 ] && [ -s "$WORK/$module.markers" ]; then
    echo "error: [$module] no diagnostics extracted although the sources carry markers; expected.txt left untouched." >&2
    PROBLEMS=$((PROBLEMS + 1))
    continue
  fi
  write_golden "$module"
  cross_check "$module" "$ROOT/$module/expected.txt"
done

for module in "${CLEAN_MODULES[@]}"; do
  if ! extract_module "$module" > "$WORK/$module.golden"; then
    PROBLEMS=$((PROBLEMS + 1))
    continue
  fi
  write_golden "$module"
  check_clean "$module"
done

echo
if [ "$PROBLEMS" -gt 0 ]; then
  echo "$PROBLEMS problem(s) - fix the corpus cases (or their markers) listed above."
  exit 1
fi
echo "Every marker agrees with javac and every clean module compiles silently."
