//! The **configuration metadata** index — what Spring itself says its properties are.
//!
//! ## Where this comes from, and why it is not a download
//!
//! Spring Boot ships a machine-readable description of every property it accepts:
//! `META-INF/spring-configuration-metadata.json`, generated at build time by the
//! annotation processor and packaged **inside each jar**. Every starter carries its own, so
//! the union of the jars on a project's classpath *is* the property vocabulary of that
//! project — including third-party starters nobody publishes a web page for.
//!
//! That makes the on-disk jars a better source than any documentation endpoint:
//!
//! - it is **version-exact** — the keys described are the ones this project's Boot version
//!   actually reads, not the ones the current docs describe;
//! - it covers **libraries**, not just Spring — a company's own starter is described the
//!   same way;
//! - it needs **no network**, so it works offline and on the first run.
//!
//! The host reads the jar entries (this crate never touches the filesystem — see
//! [`ProjectScan`]) and hands them over as text; everything below is pure parsing.
//!
//! A curated fallback ([`crate::builtin_meta`]) covers the common keys for the case where no
//! jars have been resolved yet, so the feature is useful before the first Maven resolve
//! rather than silently empty.
//!
//! [`ProjectScan`]: bennu_ext::prelude::ProjectScan
//!
//! ## Relaxed binding
//!
//! Keys are stored under [`canonical_key`] like everywhere else in this crate, so
//! `spring.jpa.showSql`, `spring.jpa.show-sql` and `SPRING_JPA_SHOW_SQL` are one entry.
//!
//! ## Map-typed properties
//!
//! `logging.level.org.hibernate` is not a declared key — the declared key is `logging.level`,
//! typed `Map<String, LogLevel>`, and everything under it is a user-chosen suffix. A lookup
//! that missed exactly therefore walks up the dotted path and accepts the nearest ancestor
//! that is a map ([`MetadataIndex::lookup`]), which is what makes hover work on a line nobody
//! could have declared in advance.

use std::collections::BTreeMap;

use serde_json::Value;

use crate::usages::canonical_key;

/// An ALL-CAPS spelling read as the property it stands for: `SERVER.PORT` → `server.port`.
///
/// `None` unless the key contains no lowercase letter at all — that is the environment-variable
/// convention, and restricting the second lookup to it means an ordinary key is never looked up
/// twice.
///
/// Underscores become dashes and dots stay dots. A true environment variable spells BOTH
/// separators `_` (`SPRING_JPA_SHOW_SQL`) and is therefore ambiguous about which is which; that
/// is deliberately not guessed at, so a key in that form simply does not match.
fn env_style_key(key: &str) -> Option<String> {
    if key.is_empty() || key.chars().any(|c| c.is_ascii_lowercase()) {
        return None;
    }
    Some(key.to_ascii_lowercase().replace('_', "-"))
}

/// The jar entry (and project resource path) that carries a module's property descriptions.
/// Generated by `spring-boot-configuration-processor` at the module's own build time.
pub const METADATA_ENTRY: &str = "META-INF/spring-configuration-metadata.json";

/// The hand-written companion a project adds for keys the processor cannot see (a key read
/// through `Environment.getProperty`, a legacy name kept for compatibility).
pub const ADDITIONAL_METADATA_ENTRY: &str =
    "META-INF/additional-spring-configuration-metadata.json";

/// Whether a path ends in either metadata file, however it is spelled by the platform.
pub fn is_metadata_path(path: &str) -> bool {
    let p = path.replace('\\', "/");
    p.ends_with(METADATA_ENTRY) || p.ends_with(ADDITIONAL_METADATA_ENTRY)
}

/// One documented property.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct PropertyMeta {
    /// The name as written in the metadata (`spring.jpa.show-sql`).
    pub name: String,
    /// Fully-qualified Java type (`java.lang.Integer`, `java.util.Map<java.lang.String,…>`).
    pub type_text: String,
    /// Prose from the declaring `@ConfigurationProperties` javadoc. May be empty.
    pub description: String,
    /// Default as documented, rendered as text. Empty when there is none.
    pub default_value: String,
    /// Why the property is deprecated, when it is. `Some("")` = deprecated with no reason
    /// given, which is still worth showing; `None` = not deprecated.
    pub deprecation: Option<String>,
    /// Key to use instead, when the deprecation names one.
    pub replacement: String,
    /// The class that declares it (`org.springframework.boot.autoconfigure.jpa.JpaProperties`).
    pub source_type: String,
    /// Which jar / file this description came from, for the hover's provenance line.
    pub origin: String,
}

impl PropertyMeta {
    /// Whether this entry describes a `Map`, i.e. whether keys nested under it are legal.
    fn is_map(&self) -> bool {
        self.type_text.starts_with("java.util.Map") || self.type_text.starts_with("Map<")
    }
}

/// One legal value for a property, from the metadata's `hints`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct HintValue {
    pub value: String,
    pub description: String,
}

/// Every property the project's dependencies describe, keyed canonically.
#[derive(Debug, Clone, Default)]
pub struct MetadataIndex {
    props: BTreeMap<String, PropertyMeta>,
    hints: BTreeMap<String, Vec<HintValue>>,
}

impl MetadataIndex {
    pub fn is_empty(&self) -> bool {
        self.props.is_empty()
    }

    pub fn len(&self) -> usize {
        self.props.len()
    }

    /// Every documented property, in canonical-key order.
    pub fn all(&self) -> impl Iterator<Item = &PropertyMeta> {
        self.props.values()
    }

    /// Fold one `spring-configuration-metadata.json` into the index.
    ///
    /// `origin` is a display label for where it came from (a jar file name). Malformed JSON
    /// is **skipped silently**: a broken descriptor in one dependency must not cost the user
    /// the vocabulary carried by the other two hundred.
    ///
    /// Later files do not overwrite earlier ones. Boot's own jars are offered first by the
    /// host, and the first description of a key is the authoritative one — a starter that
    /// re-declares `server.port` is describing the same property, not a better one.
    pub fn absorb(&mut self, json: &str, origin: &str) {
        let Ok(root) = serde_json::from_str::<Value>(json) else { return };
        for p in root.get("properties").and_then(Value::as_array).into_iter().flatten() {
            let Some(meta) = property_of(p, origin) else { continue };
            self.props.entry(canonical_key(&meta.name)).or_insert(meta);
        }
        for h in root.get("hints").and_then(Value::as_array).into_iter().flatten() {
            let Some(name) = h.get("name").and_then(Value::as_str) else { continue };
            let values: Vec<HintValue> = h
                .get("values")
                .and_then(Value::as_array)
                .into_iter()
                .flatten()
                .filter_map(hint_of)
                .collect();
            if values.is_empty() {
                continue;
            }
            // `logging.level.values` is a hint about the VALUES of `logging.level`; the
            // `.values` / `.keys` suffix is metadata grammar, not part of the key.
            let key = name.strip_suffix(".values").unwrap_or(name);
            self.hints.entry(canonical_key(key)).or_insert(values);
        }
    }

    /// Fill the gaps in this index from `other`, keeping everything already known.
    ///
    /// For folding the curated table in **behind** the jars: a real descriptor always wins,
    /// and the stand-in only covers what no jar described. A project with a complete
    /// classpath therefore never shows a hand-written entry.
    pub fn merge_defaults(&mut self, other: MetadataIndex) {
        for (key, meta) in other.props {
            self.props.entry(key).or_insert(meta);
        }
        for (key, values) in other.hints {
            self.hints.entry(key).or_insert(values);
        }
    }

    /// The description of `key`, or of the nearest map-typed ancestor that legitimises it.
    ///
    /// The second half is what makes `logging.level.com.acme` resolvable: nobody declares
    /// that key, but `logging.level` is a `Map` and so everything under it is legal.
    pub fn lookup(&self, key: &str) -> Option<&PropertyMeta> {
        if let Some(hit) = self.lookup_canonical(&canonical_key(key)) {
            return Some(hit);
        }
        // The environment-variable spelling, which `canonical_key` cannot serve: its camelCase
        // rule reads every capital as a word boundary, so `SERVER` canonicalises to `s-e-r-v-e-r`.
        // A second, narrower attempt is honest about them being two conventions rather than one.
        self.lookup_canonical(&env_style_key(key)?)
    }

    /// A canonical key, then the nearest ancestor that is a **map** — the only ancestor that can
    /// legitimise a child nothing declared.
    fn lookup_canonical(&self, canonical: &str) -> Option<&PropertyMeta> {
        if let Some(hit) = self.props.get(canonical) {
            return Some(hit);
        }
        let mut rest = canonical;
        while let Some((head, _)) = rest.rsplit_once('.') {
            match self.props.get(head) {
                Some(m) if m.is_map() => return Some(m),
                _ => rest = head,
            }
        }
        None
    }

    /// Documented keys starting with `prefix` (canonically), for completion. Capped by the
    /// caller; the order is the index's own, which is alphabetical and therefore stable.
    pub fn starting_with<'a>(&'a self, prefix: &str) -> impl Iterator<Item = &'a PropertyMeta> {
        let prefix = canonical_key(prefix);
        self.props
            .range(prefix.clone()..)
            .take_while(move |(k, _)| k.starts_with(&prefix))
            .map(|(_, v)| v)
    }

    /// The documented legal values of `key`, empty when it is not an enumerated property.
    pub fn values_for(&self, key: &str) -> &[HintValue] {
        self.hints.get(&canonical_key(key)).map(Vec::as_slice).unwrap_or_default()
    }
}

fn property_of(v: &Value, origin: &str) -> Option<PropertyMeta> {
    let name = v.get("name").and_then(Value::as_str)?.to_string();
    if name.is_empty() {
        return None;
    }
    let deprecation = v.get("deprecation").map(|d| {
        d.get("reason").and_then(Value::as_str).unwrap_or_default().to_string()
    });
    Some(PropertyMeta {
        name,
        type_text: str_at(v, "type"),
        description: str_at(v, "description"),
        default_value: v.get("defaultValue").map(render_scalar).unwrap_or_default(),
        replacement: v
            .get("deprecation")
            .map(|d| str_at(d, "replacement"))
            .unwrap_or_default(),
        deprecation,
        source_type: str_at(v, "sourceType"),
        origin: origin.to_string(),
    })
}

fn hint_of(v: &Value) -> Option<HintValue> {
    let value = v.get("value").map(render_scalar).filter(|s| !s.is_empty())?;
    Some(HintValue { value, description: str_at(v, "description") })
}

fn str_at(v: &Value, key: &str) -> String {
    v.get(key).and_then(Value::as_str).unwrap_or_default().to_string()
}

/// A JSON scalar as the user would write it in a yaml. `defaultValue` is genuinely
/// polymorphic in this format (`8080`, `"always"`, `true`, `["a","b"]`), so it is rendered
/// rather than typed.
fn render_scalar(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Null => String::new(),
        Value::Array(items) => {
            items.iter().map(render_scalar).collect::<Vec<_>>().join(", ")
        }
        other => other.to_string(),
    }
}

/// The index every project starts from, before (or without) any jars: the curated table in
/// [`crate::builtin_meta`].
pub fn builtin_index() -> MetadataIndex {
    let mut idx = MetadataIndex::default();
    for &(name, type_text, default_value, description) in crate::builtin_meta::COMMON {
        idx.props.entry(canonical_key(name)).or_insert(PropertyMeta {
            name: name.to_string(),
            type_text: type_text.to_string(),
            description: description.to_string(),
            default_value: default_value.to_string(),
            deprecation: None,
            replacement: String::new(),
            source_type: String::new(),
            origin: "Spring Boot (built-in)".to_string(),
        });
    }
    for &(key, values) in crate::builtin_meta::VALUE_HINTS {
        idx.hints.entry(canonical_key(key)).or_insert(
            values
                .iter()
                .map(|v| HintValue { value: v.to_string(), description: String::new() })
                .collect(),
        );
    }
    idx
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"{
      "groups": [{ "name": "server" }],
      "properties": [
        { "name": "server.port", "type": "java.lang.Integer",
          "description": "Server HTTP port.", "defaultValue": 8080,
          "sourceType": "org.springframework.boot.autoconfigure.web.ServerProperties" },
        { "name": "spring.jpa.show-sql", "type": "java.lang.Boolean", "defaultValue": false },
        { "name": "logging.level", "type": "java.util.Map<java.lang.String,java.lang.String>",
          "description": "Log levels severity mapping." },
        { "name": "server.servlet.context-path", "type": "java.lang.String" },
        { "name": "spring.profiles.active", "type": "java.lang.String",
          "deprecation": { "reason": "Use spring.config.activate.on-profile.",
                           "replacement": "spring.config.activate.on-profile" } }
      ],
      "hints": [
        { "name": "logging.level.values",
          "values": [{ "value": "trace", "description": "Trace level." }, { "value": "debug" }] }
      ]
    }"#;

    fn index() -> MetadataIndex {
        let mut i = MetadataIndex::default();
        i.absorb(SAMPLE, "spring-boot-autoconfigure.jar");
        i
    }

    #[test]
    fn a_declared_property_carries_its_type_default_and_prose() {
        let m = index().lookup("server.port").cloned().unwrap();
        assert_eq!(m.type_text, "java.lang.Integer");
        assert_eq!(m.default_value, "8080", "a numeric default renders as it is written");
        assert_eq!(m.description, "Server HTTP port.");
        assert_eq!(m.origin, "spring-boot-autoconfigure.jar");
        assert_eq!(index().lookup("spring.jpa.show-sql").unwrap().default_value, "false");
    }

    /// The relaxed-binding promise, on the metadata side: three spellings, one entry.
    #[test]
    fn the_lookup_is_relaxed_about_spelling() {
        let i = index();
        assert!(i.lookup("spring.jpa.showSql").is_some());
        assert!(i.lookup("spring.jpa.show_sql").is_some());
        assert!(i.lookup("SERVER.PORT").is_some(), "an env-style spelling still resolves");
    }

    /// The case nothing can declare in advance — and the one a naive exact lookup gets wrong.
    #[test]
    fn a_key_under_a_map_resolves_to_the_map_that_legitimises_it() {
        let i = index();
        let m = i.lookup("logging.level.org.hibernate.SQL").unwrap();
        assert_eq!(m.name, "logging.level");
        // The guard: a non-map ancestor must NOT swallow its children, or every typo under
        // `server.port.…` would look like a documented key.
        assert!(i.lookup("server.port.nonsense").is_none());
        assert!(i.lookup("totally.unknown").is_none());
    }

    #[test]
    fn hints_are_stored_without_the_metadata_suffix() {
        let i = index();
        let values: Vec<&str> = i.values_for("logging.level").iter().map(|h| h.value.as_str()).collect();
        assert_eq!(values, ["trace", "debug"]);
        assert!(i.values_for("server.port").is_empty());
    }

    #[test]
    fn a_deprecated_property_says_so_and_names_its_replacement() {
        let m = index().lookup("spring.profiles.active").cloned().unwrap();
        assert_eq!(m.replacement, "spring.config.activate.on-profile");
        assert!(m.deprecation.unwrap().starts_with("Use spring.config"));
    }

    #[test]
    fn completion_prefixes_match_by_canonical_key() {
        let i = index();
        let names: Vec<&str> = i.starting_with("server.").map(|m| m.name.as_str()).collect();
        assert_eq!(names, ["server.port", "server.servlet.context-path"]);
        assert_eq!(i.starting_with("serv").count(), 2);
        assert_eq!(i.starting_with("zzz").count(), 0);
    }

    /// A broken descriptor in one jar must not cost the vocabulary carried by the others.
    #[test]
    fn malformed_json_is_skipped_rather_than_poisoning_the_index() {
        let mut i = index();
        i.absorb("{ not json at all", "broken.jar");
        i.absorb("{}", "empty.jar");
        assert!(i.lookup("server.port").is_some());
    }

    #[test]
    fn the_first_description_of_a_key_wins() {
        let mut i = index();
        i.absorb(
            r#"{"properties":[{"name":"server.port","type":"java.lang.String","description":"Nope."}]}"#,
            "late.jar",
        );
        assert_eq!(i.lookup("server.port").unwrap().type_text, "java.lang.Integer");
    }

    #[test]
    fn the_builtin_table_stands_in_before_any_jar_is_resolved() {
        let i = builtin_index();
        assert!(!i.is_empty());
        let port = i.lookup("server.port").expect("the most-typed key of all");
        assert_eq!(port.type_text, "java.lang.Integer");
        assert!(i.lookup("spring.datasource.url").is_some());
        assert!(!i.values_for("logging.level").is_empty(), "log levels are enumerable");
    }
}
