/**
 * Skeletons for the objects a script creates — the editor's **Generate**.
 *
 * Not a snippet library and not a wizard: six shapes nobody remembers exactly, in
 * the dialect of the buffer they are being written into. The names are obvious
 * placeholders (`NOME_TABELLA`) precisely so that leaving one in is a mistake you
 * see rather than one that compiles.
 *
 * What earns this its own module is the dialect knowledge, which is not
 * cosmetic — the two engines disagree about almost everything here:
 *
 *  - a PostgreSQL trigger cannot exist without a `RETURNS trigger` function, so
 *    the skeleton emits **both**; an Oracle one carries its body inline;
 *  - Oracle spells a function's return `RETURN`, PostgreSQL `RETURNS`;
 *  - Oracle wants `IS … BEGIN … END;`, PostgreSQL a `$$`-quoted body with a
 *    `LANGUAGE` clause;
 *  - identity is `GENERATED BY DEFAULT AS IDENTITY` in both, but the surrounding
 *    types are not (`NUMBER` vs `bigint`, `VARCHAR2` vs `varchar`).
 *
 * Getting any of those wrong produces something that looks right and does not run,
 * which is worse than not offering it.
 */

import type { Dialect } from '$lib/types/picus';

export type SkeletonKind =
  | 'table'
  | 'view'
  | 'sequence'
  | 'trigger'
  | 'function'
  | 'procedure';

/** What the menu calls each one. */
export const SKELETON_LABELS: Record<SkeletonKind, string> = {
  table: 'Table',
  view: 'View',
  sequence: 'Sequence',
  trigger: 'Trigger',
  function: 'Function',
  procedure: 'Procedure',
};

/** Menu order: the things scripts create most often, first. */
export const SKELETON_ORDER: SkeletonKind[] = [
  'table',
  'view',
  'sequence',
  'trigger',
  'function',
  'procedure',
];

const ORACLE: Record<SkeletonKind, string> = {
  table: `CREATE TABLE NOME_TABELLA (
  ID          NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
  DESCRIZIONE VARCHAR2(255) NOT NULL,
  CREATO_IL   DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_NOME_TABELLA PRIMARY KEY (ID)
);`,
  view: `CREATE OR REPLACE VIEW NOME_VISTA AS
SELECT t.ID,
       t.DESCRIZIONE
  FROM NOME_TABELLA t
 WHERE t.CREATO_IL IS NOT NULL;`,
  sequence: `CREATE SEQUENCE NOME_SEQUENCE
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;`,
  // Oracle carries the body inline — there is no separate trigger function.
  trigger: `CREATE OR REPLACE TRIGGER NOME_TRIGGER
  BEFORE INSERT ON NOME_TABELLA
  FOR EACH ROW
BEGIN
  :NEW.CREATO_IL := SYSDATE;
END;
/`,
  function: `CREATE OR REPLACE FUNCTION NOME_FUNZIONE (
  P_ID IN NUMBER
) RETURN VARCHAR2
IS
  V_RISULTATO VARCHAR2(255);
BEGIN
  SELECT DESCRIZIONE INTO V_RISULTATO FROM NOME_TABELLA WHERE ID = P_ID;
  RETURN V_RISULTATO;
END;
/`,
  procedure: `CREATE OR REPLACE PROCEDURE NOME_PROCEDURA (
  P_ID IN NUMBER
)
IS
BEGIN
  UPDATE NOME_TABELLA SET CREATO_IL = SYSDATE WHERE ID = P_ID;
END;
/`,
};

const POSTGRES: Record<SkeletonKind, string> = {
  table: `CREATE TABLE nome_tabella (
  id          bigint       GENERATED BY DEFAULT AS IDENTITY,
  descrizione varchar(255) NOT NULL,
  creato_il   timestamp    NOT NULL DEFAULT now(),
  CONSTRAINT pk_nome_tabella PRIMARY KEY (id)
);`,
  view: `CREATE OR REPLACE VIEW nome_vista AS
SELECT t.id,
       t.descrizione
  FROM nome_tabella t
 WHERE t.creato_il IS NOT NULL;`,
  sequence: `CREATE SEQUENCE nome_sequence
  START WITH 1
  INCREMENT BY 1
  NO CYCLE;`,
  // Both halves: a trigger with no function is not a thing PostgreSQL will accept,
  // and finding that out after pasting is the failure this exists to prevent.
  trigger: `CREATE OR REPLACE FUNCTION nome_trigger_fn() RETURNS trigger AS $$
BEGIN
  NEW.creato_il := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER nome_trigger
  BEFORE INSERT ON nome_tabella
  FOR EACH ROW
  EXECUTE FUNCTION nome_trigger_fn();`,
  function: `CREATE OR REPLACE FUNCTION nome_funzione(p_id bigint)
RETURNS varchar AS $$
DECLARE
  v_risultato varchar(255);
BEGIN
  SELECT descrizione INTO v_risultato FROM nome_tabella WHERE id = p_id;
  RETURN v_risultato;
END;
$$ LANGUAGE plpgsql;`,
  procedure: `CREATE OR REPLACE PROCEDURE nome_procedura(p_id bigint) AS $$
BEGIN
  UPDATE nome_tabella SET creato_il = now() WHERE id = p_id;
END;
$$ LANGUAGE plpgsql;`,
};

/**
 * The skeleton for `kind`, in `dialect`.
 *
 * A buffer with no dialect — a portable script, or one nobody has classified —
 * gets the PostgreSQL shape, because it is the one that is closer to standard SQL
 * and therefore the smaller thing to correct. The caller knows the dialect it
 * asked with; nothing here guesses one from the text.
 */
export function skeleton(kind: SkeletonKind, dialect: Dialect | null): string {
  const table = dialect === 'oracle' ? ORACLE : POSTGRES;
  return `${table[kind]}\n`;
}
