//! Every built-in hook name, as a constant (**D10**).
//!
//! One module per namespace, each generated by [`crate::declare_hook_names!`] so the
//! namespace string is written exactly once and every name derives from it.
//! Fire sites, the catalog in [`crate::hook_catalog`], and the subscribe-time
//! validation all read from *these* constants — a name that is not here is a
//! name that cannot be fired.
//!
//! ## Choosing the namespace for a new hook
//!
//! - Does the *host runtime* own the concept (plugin lifecycle, main-area
//!   views, theme, which project is active)? → [`arbor`]. The same `main.lua`
//!   line must resolve to the same hook under every product, which is only
//!   true inside this namespace.
//! - Does one product own it? → that product's module. "Owns" means the
//!   concept, not the crate that happens to fire it: `corvus:repo_init` is
//!   Corvus's even though the shell can fire it.
//! - Is it a subsystem that is on its way to being its own crate? → its own
//!   namespace ([`pipeline`]), so the eventual extraction is a move and not a
//!   rename.
//!
//! ## The event half never repeats the namespace
//!
//! `garrulus:note_saved`, not `garrulus:vault_note_saved` — the qualifier the
//! old flat names had to carry to avoid colliding with Corvus's git notes is
//! now the namespace itself.

/// Hooks owned by the host runtime rather than by any one product.
///
/// Fired by the plugin runtime (`plugin_load` / `plugin_unload`), by the view
/// host (`view_open` / `view_close`), by the theme pipeline, and by the shared
/// project-lifecycle plumbing that every backend links.
///
/// This namespace is why subscribe-time resolution has a fallback. A plugin
/// that writes `arbor.events.on("plugin_load", …)` is loaded under whichever
/// product's host it targets; prefixing with that product would give
/// `corvus:plugin_load` in one host and `sitta:plugin_load` in another for the
/// *same source line*. Unqualified names therefore fall back to this namespace
/// when the product-qualified form is not a real hook.
pub mod arbor {
    use crate::hook_ns::PRODUCT_ARBOR;

    crate::declare_hook_names! {
        ns = PRODUCT_ARBOR;

        /// Fired once after the plugin's `main.lua` finishes executing.
        PLUGIN_LOAD = "plugin_load";
        /// Fired before the plugin is unloaded (reload, disable, shutdown).
        PLUGIN_UNLOAD = "plugin_unload";

        /// Fired when a project is opened in a tab.
        REPO_OPEN = "repo_open";
        /// Fired when a project tab is closed.
        REPO_CLOSE = "repo_close";
        /// Fired when the user activates a different project tab.
        TAB_SWITCH = "tab_switch";

        /// Targeted at the owning plugin when one of its main-area views opens.
        VIEW_OPEN = "view_open";
        /// Targeted at the owning plugin when one of its main-area views closes.
        VIEW_CLOSE = "view_close";

        /// Fired when the effective theme changes.
        THEME_CHANGED = "theme_changed";
    }
}

/// Hooks owned by Bennu, the code editor.
///
/// Bennu's concept is a FILE being edited, not a repository being open — the
/// project-lifecycle hooks it shares with every other product stay in
/// [`arbor`]. What only Bennu can say is which source the caret is in.
pub mod bennu {
    use crate::hook_ns::PRODUCT_BENNU;

    crate::declare_hook_names! {
        ns = PRODUCT_BENNU;

        /// Fired when the editor's active file changes — a tab switched to, a
        /// file opened, a file reopened from history.
        ///
        /// The event a companion panel needs: a preview, a linter or a
        /// reference pane that keeps showing the previous file is showing the
        /// wrong one, and until this existed nothing announced the change.
        FILE_OPENED = "file_opened";
        /// Fired when the editor's last file closes and nothing is being edited.
        FILE_CLOSED = "file_closed";
    }
}

/// Hooks owned by Corvus, the Git product.
pub mod corvus {
    use crate::hook_ns::PRODUCT_CORVUS;

    crate::declare_hook_names! {
        ns = PRODUCT_CORVUS;

        // ── Repo registry ────────────────────────────────────────────────
        /// A non-git folder was initialised as a repo through the Init flow.
        REPO_INIT = "repo_init";
        /// A repo was permanently removed from Arbor's registry.
        REPO_DEREGISTERED = "repo_deregistered";
        /// A registered project's path no longer resolves on disk.
        PROJECT_MISSING = "project_missing";
        /// The user pointed a missing project at a new on-disk location.
        PROJECT_RELOCATED = "project_relocated";

        // ── Branch / tag ─────────────────────────────────────────────────
        BRANCH_CREATE = "branch_create";
        BRANCH_DELETE = "branch_delete";
        BRANCH_RENAME = "branch_rename";
        CHECKOUT = "checkout";
        TAG_CREATE = "tag_create";
        TAG_DELETE = "tag_delete";

        // ── Commit / stash / rebase ──────────────────────────────────────
        /// Vetoable: a handler returning a non-empty string aborts the commit.
        PRE_COMMIT = "pre_commit";
        COMMIT = "commit";
        STASH_PUSH = "stash_push";
        STASH_POP = "stash_pop";
        REBASE_START = "rebase_start";
        REBASE_ABORT = "rebase_abort";

        // ── Remote ───────────────────────────────────────────────────────
        FETCH = "fetch";
        PUSH = "push";
        PULL = "pull";

        // ── Git notes (NOT vault notes — see `garrulus::NOTE_SAVED`) ─────
        NOTE_SAVED = "note_saved";
        NOTE_DELETED = "note_deleted";

        // ── Git Flow ─────────────────────────────────────────────────────
        FLOW_INIT = "flow_init";
        FLOW_FEATURE_START = "flow_feature_start";
        FLOW_FEATURE_FINISH = "flow_feature_finish";
        FLOW_RELEASE_START = "flow_release_start";
        FLOW_RELEASE_FINISH = "flow_release_finish";
        FLOW_HOTFIX_START = "flow_hotfix_start";
        FLOW_HOTFIX_FINISH = "flow_hotfix_finish";

        // ── Merge / pull requests ────────────────────────────────────────
        MR_OPENED = "mr_opened";
        MR_MERGED = "mr_merged";
        MR_UPDATED = "mr_updated";

        // ── Issues (Linear / Jira) ───────────────────────────────────────
        ISSUE_LINKED = "issue_linked";
        ISSUE_TRANSITIONED = "issue_transitioned";

        // ── Workspaces ───────────────────────────────────────────────────
        WORKSPACE_CREATED = "workspace_created";
        WORKSPACE_UPDATED = "workspace_updated";
        WORKSPACE_DELETED = "workspace_deleted";
        WORKSPACE_SWITCHED = "workspace_switched";
        WORKSPACE_REPO_ADDED = "workspace_repo_added";
        WORKSPACE_REPO_REMOVED = "workspace_repo_removed";

        // ── Security dashboard ───────────────────────────────────────────
        SECURITY_SUMMARY_LOADED = "security_summary_loaded";
        SECURITY_FINDING_STATE_CHANGED = "security_finding_state_changed";

        // ── Linked worktrees ─────────────────────────────────────────────
        WORKTREE_LINK_SYNC_STARTED = "worktree_link_sync_started";
        WORKTREE_LINK_SYNC_DONE = "worktree_link_sync_done";
        WORKTREE_LINK_MEMBER_ADDED = "worktree_link_member_added";
        WORKTREE_LINK_MEMBER_REMOVED = "worktree_link_member_removed";
    }
}

/// Hooks owned by Garrulus, the note-vault product.
///
/// The vault's note events no longer need the `vault_` qualifier the flat
/// names carried: `garrulus:note_saved` and `corvus:note_saved` are different
/// hooks by construction.
pub mod garrulus {
    use crate::hook_ns::PRODUCT_GARRULUS;

    crate::declare_hook_names! {
        ns = PRODUCT_GARRULUS;

        VAULT_OPENED = "vault_opened";
        VAULT_CLOSED = "vault_closed";
        TYPE_APPLIED = "type_applied";

        NOTE_CREATED = "note_created";
        NOTE_SAVED = "note_saved";
        NOTE_RENAMED = "note_renamed";
        NOTE_DELETED = "note_deleted";

        SYNC_STARTED = "sync_started";
        SYNC_DONE = "sync_done";
        SYNC_CONFLICT = "sync_conflict";
    }
}

/// Hooks owned by the pipeline engine.
///
/// Its own namespace rather than Corvus's: the engine is shell-level today and
/// is slated to become a standalone crate, so naming it after the product that
/// currently hosts it would guarantee a second rename later.
pub mod pipeline {
    crate::declare_hook_names! {
        ns = "pipeline";

        STARTED = "started";
        STEP_DONE = "step_done";
        DONE = "done";
        /// Targeted at one plugin: the host asks it to run a pipeline it owns.
        /// Delivered through `fire_on`, never broadcast.
        RUN_REQUEST = "run_request";
    }
}

/// Every namespace's `ALL` slice, so callers can walk the full name registry
/// without re-listing the namespaces.
///
/// Used by the catalog's completeness test — a namespace added here but not
/// wired into the catalog is a name that documents itself as absent.
pub const NAMESPACES: &[(&str, &[&str])] = &[
    (arbor::NS, arbor::ALL),
    (bennu::NS, bennu::ALL),
    (corvus::NS, corvus::ALL),
    (garrulus::NS, garrulus::ALL),
    (pipeline::NS, pipeline::ALL),
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn every_name_is_namespace_qualified() {
        for (ns, names) in NAMESPACES {
            for &name in *names {
                assert!(
                    name.starts_with(&format!("{ns}:")),
                    "'{name}' is not in namespace '{ns}'"
                );
            }
        }
    }

    #[test]
    fn names_are_globally_unique() {
        let mut seen: HashSet<&str> = HashSet::new();
        for (_, names) in NAMESPACES {
            for &name in *names {
                assert!(seen.insert(name), "duplicate hook name '{name}'");
            }
        }
    }

    /// The collision that motivated the namespacing must now be two distinct
    /// names rather than a convention nobody can enforce.
    #[test]
    fn git_notes_and_vault_notes_no_longer_collide() {
        assert_ne!(corvus::NOTE_SAVED, garrulus::NOTE_SAVED);
        assert_eq!(corvus::NOTE_SAVED, "corvus:note_saved");
        assert_eq!(garrulus::NOTE_SAVED, "garrulus:note_saved");
    }
}
