//! Compiles the committed Tree-sitter parser (`src/parser.c`, generated by the
//! dev-time `tree-sitter generate`) and the hand-written external scanner
//! (`src/scanner.c`) via the `cc` build dependency. No Node and no Tree-sitter
//! CLI at build time — `cargo build` needs only a C compiler, the same one the
//! workspace already requires for vendored libgit2 and mlua. Same arrangement as
//! `merula-lang`; see `README.md` → "Build workflow".

use std::path::Path;

fn main() {
    let src = Path::new("src");

    let mut build = cc::Build::new();
    build.include(src);
    build.file(src.join("parser.c"));
    build.file(src.join("scanner.c"));
    // The generated parser triggers warnings we do not own.
    build.warnings(false);
    build.flag_if_supported("-Wno-unused-parameter");
    build.flag_if_supported("-Wno-unused-but-set-variable");
    build.compile("tree-sitter-picus-sql");

    println!("cargo:rerun-if-changed=src/parser.c");
    println!("cargo:rerun-if-changed=src/scanner.c");
    println!("cargo:rerun-if-changed=src/tree_sitter/parser.h");
}
