//! Compiles the committed Tree-sitter parser (`src/parser.c`, generated by the
//! dev-time `tree-sitter generate`) and the hand-written external scanner
//! (`src/scanner.c`) into the crate via the `cc` build dependency. No Node or
//! Tree-sitter CLI is touched at build time — `cargo build` only needs a C
//! compiler, the same one the workspace already requires (vendored libgit2 /
//! mlua). See `README.md` → "Build workflow (Tree-sitter)".

use std::path::Path;

fn main() {
    let src = Path::new("src");

    let mut build = cc::Build::new();
    build.include(src);
    build.file(src.join("parser.c"));
    build.file(src.join("scanner.c"));
    // The generated parser triggers warnings we don't own; silence them so a
    // strict workspace profile stays clean.
    build.warnings(false);
    build.flag_if_supported("-Wno-unused-parameter");
    build.flag_if_supported("-Wno-unused-but-set-variable");
    build.compile("tree-sitter-grove");

    println!("cargo:rerun-if-changed=src/parser.c");
    println!("cargo:rerun-if-changed=src/scanner.c");
    println!("cargo:rerun-if-changed=src/tree_sitter/parser.h");
}
