//! Files the pack must never report on.
//!
//! A naming diagnostic is only worth showing where somebody can act on it. Generated code fails
//! both halves of that: nobody chose the names, and editing them is undone by the next build. On a
//! legacy tree the generated half is often larger than the authored one — a JAXB or JavaCC output
//! directory alone can outnumber every hand-written class — so getting this wrong does not add
//! noise to the report, it *is* the report.
//!
//! Two independent signals, because either one alone misses a real case:
//!
//! * **Where the file is.** Build outputs live in known places, and a file under
//!   `target/generated-sources` is generated no matter what it contains.
//! * **What the file says.** A generator that writes into the source tree — and plenty do —
//!   almost always stamps `@Generated` or a "do not edit" banner at the top. Only the head of the
//!   file is read: a project that merely *mentions* code generation halfway down a comment is not
//!   generated.

/// How much of a file's head is searched for a generated-code marker.
const HEAD_BYTES: usize = 4096;

/// Path segments whose contents are build output.
const GENERATED_DIRS: [&str; 6] = [
    "target/generated-sources",
    "target/generated-test-sources",
    "build/generated",
    "build/generated-sources",
    "generated-sources",
    "node_modules",
];

/// Banners a generator leaves at the top of a file it owns.
const GENERATED_MARKERS: [&str; 6] = [
    "@generated",
    "do not edit",
    "automatically generated",
    "auto-generated",
    "this file is generated",
    // Not "generated by the": real banners read `Generated by wsdl2java`, `Generated by protoc`,
    // `Code generated by …`. Requiring the article matched the one example this was written from
    // and missed every generator that does not use it.
    "generated by",
];

/// Whether `path` (forward-slashed) sits in a build-output directory.
pub fn is_generated_path(path: &str) -> bool {
    let normalised = path.replace('\\', "/").to_ascii_lowercase();
    GENERATED_DIRS.iter().any(|dir| {
        normalised.contains(&format!("/{dir}/")) || normalised.starts_with(&format!("{dir}/"))
    })
}

/// Whether the head of `source` carries a generated-code banner or a `@Generated` annotation.
pub fn is_generated_source(source: &str) -> bool {
    let mut end = HEAD_BYTES.min(source.len());
    while end > 0 && !source.is_char_boundary(end) {
        end -= 1;
    }
    let head = source[..end].to_ascii_lowercase();
    GENERATED_MARKERS.iter().any(|marker| head.contains(marker))
}

/// Whether this file is generated, by either signal.
pub fn is_generated(path: &str, source: &str) -> bool {
    is_generated_path(path) || is_generated_source(source)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_output_directories_are_generated() {
        assert!(is_generated_path("target/generated-sources/jaxb/Order.java"));
        assert!(is_generated_path("web/target/generated-sources/Foo.java"));
        assert!(is_generated_path("C:/proj/build/generated/Bar.java"));
        assert!(is_generated_path("app\\target\\generated-sources\\Baz.java"));
        assert!(!is_generated_path("src/main/java/com/acme/Order.java"));
    }

    #[test]
    fn a_directory_merely_named_like_one_does_not_count() {
        // The segment must be a whole path segment, not a substring of a longer name.
        assert!(!is_generated_path("src/generated-sources-notes/Order.java"));
    }

    #[test]
    fn banners_in_the_head_are_generated() {
        assert!(is_generated_source("// Generated by the JAXB compiler\nclass A {}"));
        assert!(is_generated_source("/* DO NOT EDIT — regenerate instead */\nclass A {}"));
        assert!(is_generated_source("@Generated(\"javacc\")\npublic class A {}"));
        assert!(!is_generated_source("package com.acme;\nclass Order {}"));
    }

    #[test]
    fn a_marker_far_down_the_file_is_not_a_banner() {
        let source = format!("class A {{\n{}\n// do not edit\n}}", "// filler\n".repeat(600));
        assert!(!is_generated_source(&source));
    }

    #[test]
    fn head_scan_never_splits_a_char() {
        // A multi-byte character straddling the cut must not panic.
        let source = format!("{}è tutto", "a".repeat(HEAD_BYTES - 1));
        assert!(!is_generated_source(&source));
    }
}
