//! The SQL a held result is made of — pure, no client, fully unit-tested.
//!
//! Every string a cursor operation sends to the server is built here, and the
//! **cursor name is never the caller's**: it is generated by
//! [`CursorRegistry`](super::registry::CursorRegistry), looked up there, and only
//! the looked-up value reaches these functions. That is what makes an identifier in
//! a `DECLARE` safe without trusting anything that arrived over the wire — and it
//! is quoted here as well, because a defence that depends on two things being true
//! elsewhere is not a defence.

use crate::sql::{
    leading_keyword, quote_ident, quote_qualified, single_statement, statement_kind,
    strip_leading_noise, StatementKind,
};

/// What [`plan_execution`] decided a statement is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionPlan<'a> {
    /// One query, and one a cursor can be declared over. The body carries no
    /// terminating `;` — `DECLARE … FOR SELECT 1;` is a syntax error.
    Cursor(&'a str),
    /// Anything else: run it as the user wrote it, hold nothing.
    ///
    /// Writes, session commands (`SET`), a multi-statement paste, and the reads
    /// PostgreSQL will not accept in a `DECLARE` (`SHOW`, `EXPLAIN`, `FETCH`) all
    /// land here. It is the safe answer, not the failure answer: an unclassifiable
    /// statement runs exactly as typed, and any error the server reports quotes the
    /// user's own SQL rather than Picus's rewrite of it.
    Direct,
}

/// Decide how [`execute`](crate::session::PgSession) will run a statement.
///
/// Deliberately conservative: it only claims `Cursor` for a *single* statement whose
/// leading keyword is one PostgreSQL accepts as a cursor's query. Being wrong in
/// that direction costs a `DECLARE` that fails; being wrong in the other costs only
/// scrolling, which is why every ambiguity resolves to [`ExecutionPlan::Direct`].
pub fn plan_execution(sql: &str) -> ExecutionPlan<'_> {
    let Some(body) = single_statement(sql) else { return ExecutionPlan::Direct };
    if statement_kind(body) != StatementKind::Read {
        return ExecutionPlan::Direct;
    }
    // `DECLARE … CURSOR FOR` takes a *query*: SELECT, VALUES or TABLE. `SHOW`,
    // `EXPLAIN` and `FETCH` are reads but not queries, and would fail the DECLARE.
    match leading_keyword(strip_leading_noise(body)).as_str() {
        "SELECT" | "WITH" | "VALUES" | "TABLE" => ExecutionPlan::Cursor(body),
        _ => ExecutionPlan::Direct,
    }
}

/// `DECLARE … SCROLL CURSOR WITH HOLD FOR <body>`.
///
/// **`WITH HOLD` is the load-bearing word, and it is a trade** (see the crate
/// README): the cursor outlives the transaction that declared it, which is the only
/// form that works when several query tabs share one connection — but the server
/// pays for that by materialising the whole result into a tuplestore.
///
/// `SCROLL` because the grid is virtualised and the user may drag the scrollbar to
/// the end: a window is asked for by absolute offset, backwards as readily as
/// forwards.
///
/// The newline before the body keeps a leading `--` comment from commenting out the
/// statement; nothing is appended after it, so a *trailing* comment is harmless.
pub fn declare_cursor(name: &str, body: &str) -> String {
    format!("DECLARE {} SCROLL CURSOR WITH HOLD FOR\n{body}", quote_ident(name))
}

/// Position at `offset` and read `limit` rows — as **one** statement string.
///
/// One string rather than two calls on purpose. A connection serves several tabs;
/// a `MOVE` and its `FETCH` sent separately could have another window's `MOVE`
/// land between them and silently return rows from somewhere else. Sent together
/// they run in a single implicit transaction and cannot be interleaved.
///
/// `MOVE ABSOLUTE k` leaves the cursor *on* the k-th row (1-based), so the next
/// `FETCH FORWARD` starts at the zero-based offset `k`. `MOVE ABSOLUTE 0` means
/// "before the first row", which is the same statement with `k = 0` — no special
/// case.
pub fn window_statements(name: &str, offset: u64, limit: u32) -> String {
    let quoted = quote_ident(name);
    // `MOVE` takes a bigint. An offset beyond that is a scrollbar bug, not a
    // question worth asking the server: clamp it and let the FETCH return nothing.
    let offset = offset.min(i64::MAX as u64);
    format!("MOVE ABSOLUTE {offset} FROM {quoted}; FETCH FORWARD {limit} FROM {quoted}")
}

/// Count a held result exactly, by walking it: `MOVE FORWARD ALL` reports how many
/// rows it moved over, and `MOVE` transfers no data.
///
/// Deliberately **not** `SELECT count(*) FROM (<body>)`, which was the obvious
/// implementation and is the wrong one twice over:
///
/// * it re-executes the query, so it answers about a *different* moment — a count
///   that disagrees with the result being scrolled gives the grid a length that is
///   simply false, and it will ask for rows that are not there;
/// * it is a second full scan, where this walks a result the server has already
///   materialised.
///
/// The rewind first makes it independent of wherever the last window left the
/// cursor. It leaves the cursor at the end, which costs nothing: every window
/// positions itself absolutely before reading.
pub fn count_statements(name: &str) -> String {
    let quoted = quote_ident(name);
    format!("MOVE ABSOLUTE 0 FROM {quoted}; MOVE FORWARD ALL FROM {quoted}")
}

/// `CLOSE <name>` — releases the server-side tuplestore.
pub fn close_statement(name: &str) -> String {
    format!("CLOSE {}", quote_ident(name))
}

/// `EXPLAIN <body>` — planning only, so it is safe on a read-only session and does
/// not run the query. Its first line carries the estimate the scrollbar starts with.
pub fn explain_statement(body: &str) -> String {
    format!("EXPLAIN\n{body}")
}

/// The planner's row estimate, read out of `EXPLAIN`'s first line.
///
/// Text output rather than `FORMAT JSON` so no JSON parser is needed in a crate
/// that deliberately has none. The shape is stable and has been for a decade:
/// `Seq Scan on orders  (cost=0.00..18.50 rows=850 width=36)`. `None` when the line
/// carries no estimate, which must render as "unknown" — never as zero, which would
/// tell the user their table is empty.
pub fn plan_row_estimate(explain_first_line: &str) -> Option<i64> {
    let after = explain_first_line.split("rows=").nth(1)?;
    let digits: String = after.chars().take_while(|c| c.is_ascii_digit()).collect();
    digits.parse().ok()
}

/// `SELECT * FROM <relation>` for a relation named the way the schema tree names it.
///
/// An unqualified name is pinned to the session's schema; a qualified one is
/// honoured as written. Quoting is the point of the function — this is the one place
/// a name from the catalogue (or from a user who typed it) becomes SQL text.
pub fn relation_query(schema: &str, relation: &str) -> String {
    let target = if relation.contains('.') {
        quote_qualified(relation)
    } else {
        format!("{}.{}", quote_ident(schema), quote_ident(relation))
    };
    format!("SELECT * FROM {target}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_single_read_is_cursored_without_its_terminator() {
        // The `;` must not survive: `DECLARE … FOR SELECT 1;` does not parse.
        assert_eq!(plan_execution("SELECT * FROM orders;"), ExecutionPlan::Cursor("SELECT * FROM orders"));
        assert_eq!(plan_execution("  select 1  "), ExecutionPlan::Cursor("select 1"));
        assert_eq!(
            plan_execution("WITH x AS (SELECT 1) SELECT * FROM x"),
            ExecutionPlan::Cursor("WITH x AS (SELECT 1) SELECT * FROM x")
        );
        assert_eq!(plan_execution("VALUES (1),(2)"), ExecutionPlan::Cursor("VALUES (1),(2)"));
        assert_eq!(plan_execution("TABLE orders"), ExecutionPlan::Cursor("TABLE orders"));
    }

    #[test]
    fn a_leading_comment_does_not_hide_the_query() {
        assert_eq!(
            plan_execution("-- the daily list\nSELECT * FROM orders"),
            ExecutionPlan::Cursor("-- the daily list\nSELECT * FROM orders"),
            "the body keeps the comment; only the classification looks past it"
        );
    }

    #[test]
    fn what_cannot_be_cursored_runs_directly() {
        // Reads PostgreSQL will not accept as a cursor's query…
        assert_eq!(plan_execution("SHOW search_path"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("EXPLAIN SELECT 1"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("FETCH ALL FROM c"), ExecutionPlan::Direct);
        // …writes and session commands, which hold nothing…
        assert_eq!(plan_execution("UPDATE t SET a = 1"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("SET search_path TO x"), ExecutionPlan::Direct);
        assert_eq!(
            plan_execution("WITH d AS (DELETE FROM t RETURNING *) SELECT * FROM d"),
            ExecutionPlan::Direct,
            "a data-modifying CTE is a write, whatever it looks like"
        );
        // …and a paste of several statements, which is not one result.
        assert_eq!(plan_execution("SELECT 1; SELECT 2"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("   "), ExecutionPlan::Direct);
        assert_eq!(plan_execution("SELECT 'oops"), ExecutionPlan::Direct, "unterminated literal");
    }

    #[test]
    fn a_semicolon_inside_a_literal_does_not_make_it_multi_statement() {
        assert_eq!(
            plan_execution("SELECT 'a;b' AS x"),
            ExecutionPlan::Cursor("SELECT 'a;b' AS x"),
            "otherwise a perfectly ordinary query would lose its scrolling"
        );
    }

    #[test]
    fn the_declaration_holds_and_scrolls() {
        let out = declare_cursor("picus_cur_1", "SELECT * FROM orders");
        assert_eq!(out, "DECLARE \"picus_cur_1\" SCROLL CURSOR WITH HOLD FOR\nSELECT * FROM orders");
    }

    #[test]
    fn a_body_opening_with_a_comment_is_not_commented_out() {
        // Without the newline the whole statement would be one `--` comment.
        let out = declare_cursor("c", "-- note\nSELECT 1");
        assert!(out.contains("FOR\n-- note\nSELECT 1"), "{out}");
    }

    #[test]
    fn a_window_positions_absolutely_then_reads_forward() {
        assert_eq!(
            window_statements("picus_cur_2", 500, 201),
            "MOVE ABSOLUTE 500 FROM \"picus_cur_2\"; FETCH FORWARD 201 FROM \"picus_cur_2\""
        );
        // Offset 0 is the same statement, not a special case.
        assert_eq!(
            window_statements("c", 0, 10),
            "MOVE ABSOLUTE 0 FROM \"c\"; FETCH FORWARD 10 FROM \"c\""
        );
    }

    #[test]
    fn an_absurd_offset_is_clamped_rather_than_sent() {
        let out = window_statements("c", u64::MAX, 10);
        assert!(out.contains(&format!("MOVE ABSOLUTE {} FROM", i64::MAX)), "{out}");
    }

    #[test]
    fn counting_rewinds_then_walks() {
        assert_eq!(
            count_statements("c"),
            "MOVE ABSOLUTE 0 FROM \"c\"; MOVE FORWARD ALL FROM \"c\""
        );
    }

    #[test]
    fn a_hostile_cursor_name_cannot_escape_its_identifier() {
        // Names are generated, never received — but the quoting is what makes that
        // a defence in depth rather than a promise.
        let out = declare_cursor(r#"x"; DROP TABLE y; --"#, "SELECT 1");
        assert!(out.starts_with(r#"DECLARE "x""; DROP TABLE y; --" SCROLL"#), "{out}");
        assert!(close_statement(r#"a"b"#).starts_with(r#"CLOSE "a""b""#));
    }

    #[test]
    fn the_row_estimate_is_read_out_of_the_first_plan_line() {
        assert_eq!(
            plan_row_estimate("Seq Scan on orders  (cost=0.00..18.50 rows=850 width=36)"),
            Some(850)
        );
        assert_eq!(
            plan_row_estimate("Limit  (cost=0.00..0.04 rows=1 width=4)"),
            Some(1)
        );
        assert_eq!(plan_row_estimate("Result  (cost=0.00..0.01 width=4)"), None);
        assert_eq!(plan_row_estimate(""), None, "unknown, and it must not read as zero");
    }

    #[test]
    fn a_relation_is_quoted_and_qualified_by_the_engine() {
        assert_eq!(relation_query("public", "orders"), r#"SELECT * FROM "public"."orders""#);
        // Already qualified: honoured as written, not pinned to the session schema.
        assert_eq!(relation_query("public", "audit.log"), r#"SELECT * FROM "audit"."log""#);
        // Mixed case survives, which is the entire reason for quoting on PostgreSQL.
        assert_eq!(relation_query("public", "Orders"), r#"SELECT * FROM "public"."Orders""#);
        assert_eq!(
            relation_query("public", r#"x"; DROP TABLE y; --"#),
            r#"SELECT * FROM "public"."x""; DROP TABLE y; --""#
        );
    }

    #[test]
    fn a_relation_query_is_itself_cursorable() {
        // The relation tab and the query tab must end up on the same path, or the
        // product has two behaviours for one thing.
        let sql = relation_query("public", "orders");
        assert!(matches!(plan_execution(&sql), ExecutionPlan::Cursor(_)));
    }

    #[test]
    fn explain_does_not_run_the_query() {
        let out = explain_statement("SELECT 1");
        assert!(out.starts_with("EXPLAIN\n"), "{out}");
        assert!(!out.contains("ANALYZE"), "ANALYZE would execute it");
    }
}
