//! The SQL a held result is made of — pure, no client, fully unit-tested.
//!
//! Every string a cursor operation sends to the server is built here, and the
//! **cursor name is never the caller's**: it is generated by
//! [`CursorRegistry`](super::registry::CursorRegistry), looked up there, and only
//! the looked-up value reaches these functions. That is what makes an identifier in
//! a `DECLARE` safe without trusting anything that arrived over the wire — and it
//! is quoted here as well, because a defence that depends on two things being true
//! elsewhere is not a defence.

use crate::sql::{
    block_comment_end, leading_keyword, quote_ident, quote_qualified, single_statement,
    statement_kind, strip_leading_noise, StatementKind,
};

/// What [`plan_execution`] decided a statement is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExecutionPlan<'a> {
    /// One query, and one a cursor can be declared over. The body carries no
    /// terminating `;` — `DECLARE … FOR SELECT 1;` is a syntax error.
    Cursor(&'a str),
    /// Anything else: run it as the user wrote it, hold nothing.
    ///
    /// Writes, session commands (`SET`), a multi-statement paste, and the reads
    /// PostgreSQL will not accept in a `DECLARE` (`SHOW`, `EXPLAIN`, `FETCH`) all
    /// land here. It is the safe answer, not the failure answer: an unclassifiable
    /// statement runs exactly as typed, and any error the server reports quotes the
    /// user's own SQL rather than Picus's rewrite of it.
    Direct,
}

/// Decide how [`execute`](crate::session::PgSession) will run a statement.
///
/// Deliberately conservative: it only claims `Cursor` for a *single* statement whose
/// leading keyword is one PostgreSQL accepts as a cursor's query. Being wrong in
/// that direction costs a `DECLARE` that fails; being wrong in the other costs only
/// scrolling, which is why every ambiguity resolves to [`ExecutionPlan::Direct`].
pub fn plan_execution(sql: &str) -> ExecutionPlan<'_> {
    let Some(body) = single_statement(sql) else { return ExecutionPlan::Direct };
    if statement_kind(body) != StatementKind::Read {
        return ExecutionPlan::Direct;
    }
    // `DECLARE … CURSOR FOR` takes a *query*: SELECT, VALUES or TABLE. `SHOW`,
    // `EXPLAIN` and `FETCH` are reads but not queries, and would fail the DECLARE.
    match leading_keyword(strip_leading_noise(body)).as_str() {
        "SELECT" | "WITH" | "VALUES" | "TABLE" => ExecutionPlan::Cursor(body),
        _ => ExecutionPlan::Direct,
    }
}

/// `DECLARE … SCROLL CURSOR WITH HOLD FOR <body>`.
///
/// **`WITH HOLD` is the load-bearing word, and it is a trade** (see the crate
/// README): the cursor outlives the transaction that declared it, which is the only
/// form that works when several query tabs share one connection — but the server
/// pays for that by materialising the whole result into a tuplestore.
///
/// `SCROLL` because the grid is virtualised and the user may drag the scrollbar to
/// the end: a window is asked for by absolute offset, backwards as readily as
/// forwards.
///
/// The newline before the body keeps a leading `--` comment from commenting out the
/// statement; nothing is appended after it, so a *trailing* comment is harmless.
pub fn declare_cursor(name: &str, body: &str) -> String {
    format!("DECLARE {} SCROLL CURSOR WITH HOLD FOR\n{body}", quote_ident(name))
}

/// Position at `offset` and read `limit` rows — as **one** statement string.
///
/// One string rather than two calls on purpose. A connection serves several tabs;
/// a `MOVE` and its `FETCH` sent separately could have another window's `MOVE`
/// land between them and silently return rows from somewhere else. Sent together
/// they run in a single implicit transaction and cannot be interleaved.
///
/// `MOVE ABSOLUTE k` leaves the cursor *on* the k-th row (1-based), so the next
/// `FETCH FORWARD` starts at the zero-based offset `k`. `MOVE ABSOLUTE 0` means
/// "before the first row", which is the same statement with `k = 0` — no special
/// case.
pub fn window_statements(name: &str, offset: u64, limit: u32) -> String {
    let quoted = quote_ident(name);
    // `MOVE` takes a bigint. An offset beyond that is a scrollbar bug, not a
    // question worth asking the server: clamp it and let the FETCH return nothing.
    let offset = offset.min(i64::MAX as u64);
    format!("MOVE ABSOLUTE {offset} FROM {quoted}; FETCH FORWARD {limit} FROM {quoted}")
}

/// The first window of a statement, **without materialising the rest of it and
/// without rewriting a word of it**.
///
/// A cursor *without* `HOLD` is the one that streams: it executes incrementally,
/// so `FETCH FORWARD n` costs n rows rather than the whole table. It only lives
/// inside a transaction — which is exactly what the four statements here are for.
///
/// ## Why a transaction is safe here and not for the scrolling cursor
///
/// The objection to transactions in this module is that a session is one backend
/// shared by every query tab, so a transaction left open would enclose other tabs'
/// statements. This one is not left open: `BEGIN` and `COMMIT` are in the **same
/// string**, so they cross the wire as one round trip and nothing can interleave
/// between them.
///
/// ## Why the body is not touched
///
/// The obvious alternative — `SELECT * FROM (<body>) LIMIT n` — reorders things.
/// PostgreSQL does not promise to preserve a sub-select's `ORDER BY`, so wrapping
/// a statement the user ordered deliberately can hand back rows in another order,
/// which is a far worse bug than a slow query. Here the body is what is declared,
/// verbatim: its `ORDER BY`, its own `LIMIT`, its locking clause, all exactly as
/// written.
///
/// The newlines around it are the comment cases: a `--` on the body's last line
/// must not comment out the terminator that follows it.
///
/// ## The caller must roll back if this fails
///
/// `BEGIN` will have executed. If a later statement in the string fails,
/// PostgreSQL leaves the session in an aborted transaction block and refuses
/// everything on that connection until it is ended — see
/// [`open_result`](crate::session::PgSession) for the `ROLLBACK` that pays for
/// this.
///
/// `name` is generated by the registry, never fixed and never the caller's: two
/// reads can be in flight on one connection, and a `DECLARE` onto a name that
/// already exists is an error.
pub fn first_window_statements(name: &str, body: &str, limit: u32) -> String {
    let name = quote_ident(name);
    format!(
        "BEGIN; DECLARE {name} NO SCROLL CURSOR FOR\n{body}\n; \
         FETCH FORWARD {limit} FROM {name}; CLOSE {name}; COMMIT"
    )
}

/// `body` bounded to `limit` rows, or `None` when a `LIMIT` cannot be appended to
/// it without changing what it means.
///
/// ## Why the bound has to be in the statement and not only in the `FETCH`
///
/// A `FETCH FORWARD 501` is invisible to the planner. For `SELECT … ORDER BY x`
/// that is the whole difference between a **top-N sort**, which keeps five hundred
/// rows in memory, and a **full sort of the table**, which spills every row —
/// including every megabyte of every large object — to a temporary file before it
/// will return the first one. A cursor's own `cursor_tuple_fraction` does not help:
/// a sort is all-or-nothing unless a real `LIMIT` bounds it.
///
/// That is why an ordered query answered in seconds in another client and appeared
/// to hang here. The other client puts the bound in the SQL.
///
/// `None` for a statement that already carries its own `LIMIT`, `OFFSET`,
/// `FETCH FIRST` or locking clause: appending after any of those is a syntax error,
/// and a statement that already bounds itself does not need this.
pub fn bounded_body(body: &str, limit: u32) -> Option<String> {
    if has_top_level(body, &["LIMIT", "OFFSET", "FETCH", "FOR"]) {
        return None;
    }
    // The newline is the comment case: a `--` on the last line would otherwise
    // swallow the bound.
    Some(format!("{body}\nLIMIT {limit}"))
}

/// Does this statement order its own rows?
///
/// The question decides whether Picus may wrap it to mask large objects. It may
/// not: PostgreSQL is free to plan a sub-select's rows in any order it likes when
/// the outer query does not ask for one — a parallel plan will use `Gather` rather
/// than `Gather Merge` and interleave them — so wrapping a statement somebody
/// ordered deliberately can hand the rows back shuffled.
///
/// **Ordering wins over masking.** A grid in the wrong order is a wrong answer; an
/// ordered read that carries its large objects is merely a slow one, and it is
/// bounded by [`bounded_body`] to the window being shown.
pub fn orders_its_own_rows(body: &str) -> bool {
    has_top_level(body, &["ORDER"])
}

/// Does one of `words` appear as a **top-level** keyword of `body`?
///
/// Top level means outside every parenthesis — so the `ORDER BY` of a window
/// function or of a subquery is not one — and outside string literals, quoted
/// identifiers, dollar-quoted bodies and comments, so no text that merely *reads*
/// like a clause is mistaken for one.
fn has_top_level(body: &str, words: &[&str]) -> bool {
    let bytes = body.as_bytes();
    let mut depth = 0i32;
    let mut i = 0usize;

    while i < bytes.len() {
        let rest = &body[i..];
        if rest.starts_with("--") {
            i = rest.find('\n').map(|n| i + n + 1).unwrap_or(bytes.len());
            continue;
        }
        if rest.starts_with("/*") {
            match block_comment_end(body, i) {
                Some(end) => i = end,
                None => return false,
            }
            continue;
        }
        match bytes[i] {
            b'(' => {
                depth += 1;
                i += 1;
            }
            b')' => {
                depth -= 1;
                i += 1;
            }
            q @ (b'\'' | b'"') => {
                i += 1;
                while i < bytes.len() {
                    if bytes[i] == q {
                        if bytes.get(i + 1) == Some(&q) {
                            i += 2;
                            continue;
                        }
                        i += 1;
                        break;
                    }
                    i += 1;
                }
            }
            b'$' => {
                // A dollar-quoted body, or a `$1` parameter. Either way, stepping
                // over the tag is what keeps its contents out of the scan.
                match dollar_tag(body, i) {
                    Some(tag) => match body[i + tag.len()..].find(tag) {
                        Some(at) => i += tag.len() + at + tag.len(),
                        None => return false,
                    },
                    None => i += 1,
                }
            }
            c if c.is_ascii_alphabetic() || c == b'_' => {
                let start = i;
                while i < bytes.len()
                    && (bytes[i].is_ascii_alphanumeric() || bytes[i] == b'_' || bytes[i] == b'$')
                {
                    i += 1;
                }
                if depth == 0 {
                    let word = &body[start..i];
                    if words.iter().any(|w| word.eq_ignore_ascii_case(w)) {
                        return true;
                    }
                }
            }
            _ => i += 1,
        }
    }
    false
}

/// The dollar-quote tag opening at `at` (`$$`, `$body$`), or `None` when this `$`
/// opens no tag — a `$1` parameter does not, because a tag may not start with a
/// digit.
fn dollar_tag(sql: &str, at: usize) -> Option<&str> {
    let b = sql.as_bytes();
    if b.get(at + 1).is_some_and(|c| c.is_ascii_digit()) {
        return None;
    }
    let mut j = at + 1;
    while j < b.len() {
        if b[j] == b'$' {
            return Some(&sql[at..j + 1]);
        }
        if !(b[j].is_ascii_alphanumeric() || b[j] == b'_') {
            return None;
        }
        j += 1;
    }
    None
}

/// `body` with its large objects standing for themselves.
///
/// The **one** place a statement is rewritten, and only ever for this reason. It
/// wraps rather than editing the projection in place, so it works for any shape a
/// subquery accepts — a join, a union, a CTE — without this module needing to
/// understand one word of it. The column list comes from the server's own
/// description of the result (see [`masked_projection`]), not from parsing.
pub fn masked_source(body: &str, columns: &[(String, bool)]) -> String {
    format!("SELECT {} FROM (\n{body}\n) AS picus_src", masked_projection(columns))
}

/// `count(*)` over the same statement, for a result no cursor has been declared
/// over yet.
///
/// Deliberately different from [`count_statements`], and the difference is the
/// point: that one walks a result the server already holds, this one asks a
/// question about a statement nothing has been materialised for. It is the cheap
/// half of the pair — `count(*)` does not need any of the columns, so a table
/// whose rows are megabytes of `bytea` is counted without reading one of them.
///
/// It answers about a *different execution* than the rows on screen. That is
/// honest here in a way it would not be over a held cursor: until the cursor
/// exists there is no snapshot for it to disagree with, and the number it replaces
/// is the planner's guess.
pub fn count_query(body: &str) -> String {
    format!("SELECT count(*) FROM (\n{body}\n) AS picus_total")
}

/// Count a held result exactly, by walking it: `MOVE FORWARD ALL` reports how many
/// rows it moved over, and `MOVE` transfers no data.
///
/// Deliberately **not** `SELECT count(*) FROM (<body>)`, which was the obvious
/// implementation and is the wrong one twice over:
///
/// * it re-executes the query, so it answers about a *different* moment — a count
///   that disagrees with the result being scrolled gives the grid a length that is
///   simply false, and it will ask for rows that are not there;
/// * it is a second full scan, where this walks a result the server has already
///   materialised.
///
/// The rewind first makes it independent of wherever the last window left the
/// cursor. It leaves the cursor at the end, which costs nothing: every window
/// positions itself absolutely before reading.
pub fn count_statements(name: &str) -> String {
    let quoted = quote_ident(name);
    format!("MOVE ABSOLUTE 0 FROM {quoted}; MOVE FORWARD ALL FROM {quoted}")
}

/// `CLOSE <name>` — releases the server-side tuplestore.
pub fn close_statement(name: &str) -> String {
    format!("CLOSE {}", quote_ident(name))
}

/// `EXPLAIN <body>` — planning only, so it is safe on a read-only session and does
/// not run the query. Its first line carries the estimate the scrollbar starts with.
pub fn explain_statement(body: &str) -> String {
    format!("EXPLAIN\n{body}")
}

/// The planner's row estimate, read out of `EXPLAIN`'s first line.
///
/// Text output rather than `FORMAT JSON` so no JSON parser is needed in a crate
/// that deliberately has none. The shape is stable and has been for a decade:
/// `Seq Scan on orders  (cost=0.00..18.50 rows=850 width=36)`. `None` when the line
/// carries no estimate, which must render as "unknown" — never as zero, which would
/// tell the user their table is empty.
pub fn plan_row_estimate(explain_first_line: &str) -> Option<i64> {
    let after = explain_first_line.split("rows=").nth(1)?;
    let digits: String = after.chars().take_while(|c| c.is_ascii_digit()).collect();
    digits.parse().ok()
}

/// `SELECT * FROM <relation>` for a relation named the way the schema tree names it.
///
/// An unqualified name is pinned to the session's schema; a qualified one is
/// honoured as written. Quoting is the point of the function — this is the one place
/// a name from the catalogue (or from a user who typed it) becomes SQL text.
pub fn relation_query(schema: &str, relation: &str) -> String {
    format!("SELECT * FROM {}", relation_target(schema, relation))
}

/// The quoted, schema-pinned target of a relation query.
pub fn relation_target(schema: &str, relation: &str) -> String {
    if relation.contains('.') {
        quote_qualified(relation)
    } else {
        format!("{}.{}", quote_ident(schema), quote_ident(relation))
    }
}

/// The projection that replaces a `*`, with the large objects standing for
/// themselves rather than being fetched.
///
/// The reason this exists rather than a `SELECT *`: reading a table with a `bytea`
/// column in it pulls **every byte of every row** to draw a grid that cannot show
/// any of it. On a table of scanned documents that is the difference between a tab
/// that opens and one that appears to hang.
///
/// ## `pg_column_size`, and what it costs to be exact instead
///
/// `octet_length` is the honest length of the value — and getting it means
/// **detoasting every row**: fetching each document out of the TOAST table and
/// decompressing it, which is nearly the whole cost the masking exists to avoid.
/// `pg_column_size` reads the 18-byte TOAST pointer that sits in the heap tuple and
/// returns the *stored* size without touching the value at all, so it is constant
/// time per row.
///
/// The consequence, stated plainly: for a compressible value the figure in the grid
/// is smaller than the value really is. For the values this feature is for — scans,
/// images, PDFs, anything already compressed — the two agree to within a few bytes,
/// because `pglz` gives up on incompressible data and stores it as it came. The
/// exact length is on the value itself, which the on-demand read reports when the
/// cell is opened.
///
/// The name is preserved with an alias, so the grid's column list, the export and
/// the on-demand read all still speak of `ALLEGATO` rather than of an expression.
pub fn masked_projection(columns: &[(String, bool)]) -> String {
    columns
        .iter()
        .map(|(name, heavy)| {
            let id = quote_ident(name);
            if *heavy {
                format!("pg_column_size({id}) AS {id}")
            } else {
                id
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Is a column one whose value should not be fetched to fill a grid?
///
/// A closed list of **large-object** type names, not a size heuristic. `text` is
/// not on it and must not be: on PostgreSQL it is what ordinary strings are stored
/// in, and masking those would empty the grid of the data people came to read.
///
/// Fed from the server's own description of the result — `Type::name()` — so it
/// answers about the column that actually came back rather than about the
/// catalogue's opinion of some table.
pub fn is_large_object(data_type: &str) -> bool {
    let t = data_type.trim().to_ascii_lowercase();
    matches!(
        t.as_str(),
        "bytea" | "blob" | "clob" | "nclob" | "raw" | "long raw" | "long" | "oid" | "bfile"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_single_read_is_cursored_without_its_terminator() {
        // The `;` must not survive: `DECLARE … FOR SELECT 1;` does not parse.
        assert_eq!(plan_execution("SELECT * FROM orders;"), ExecutionPlan::Cursor("SELECT * FROM orders"));
        assert_eq!(plan_execution("  select 1  "), ExecutionPlan::Cursor("select 1"));
        assert_eq!(
            plan_execution("WITH x AS (SELECT 1) SELECT * FROM x"),
            ExecutionPlan::Cursor("WITH x AS (SELECT 1) SELECT * FROM x")
        );
        assert_eq!(plan_execution("VALUES (1),(2)"), ExecutionPlan::Cursor("VALUES (1),(2)"));
        assert_eq!(plan_execution("TABLE orders"), ExecutionPlan::Cursor("TABLE orders"));
    }

    #[test]
    fn a_leading_comment_does_not_hide_the_query() {
        assert_eq!(
            plan_execution("-- the daily list\nSELECT * FROM orders"),
            ExecutionPlan::Cursor("-- the daily list\nSELECT * FROM orders"),
            "the body keeps the comment; only the classification looks past it"
        );
    }

    #[test]
    fn what_cannot_be_cursored_runs_directly() {
        // Reads PostgreSQL will not accept as a cursor's query…
        assert_eq!(plan_execution("SHOW search_path"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("EXPLAIN SELECT 1"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("FETCH ALL FROM c"), ExecutionPlan::Direct);
        // …writes and session commands, which hold nothing…
        assert_eq!(plan_execution("UPDATE t SET a = 1"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("SET search_path TO x"), ExecutionPlan::Direct);
        assert_eq!(
            plan_execution("WITH d AS (DELETE FROM t RETURNING *) SELECT * FROM d"),
            ExecutionPlan::Direct,
            "a data-modifying CTE is a write, whatever it looks like"
        );
        // …and a paste of several statements, which is not one result.
        assert_eq!(plan_execution("SELECT 1; SELECT 2"), ExecutionPlan::Direct);
        assert_eq!(plan_execution("   "), ExecutionPlan::Direct);
        assert_eq!(plan_execution("SELECT 'oops"), ExecutionPlan::Direct, "unterminated literal");
    }

    #[test]
    fn a_semicolon_inside_a_literal_does_not_make_it_multi_statement() {
        assert_eq!(
            plan_execution("SELECT 'a;b' AS x"),
            ExecutionPlan::Cursor("SELECT 'a;b' AS x"),
            "otherwise a perfectly ordinary query would lose its scrolling"
        );
    }

    #[test]
    fn the_declaration_holds_and_scrolls() {
        let out = declare_cursor("picus_cur_1", "SELECT * FROM orders");
        assert_eq!(out, "DECLARE \"picus_cur_1\" SCROLL CURSOR WITH HOLD FOR\nSELECT * FROM orders");
    }

    #[test]
    fn a_body_opening_with_a_comment_is_not_commented_out() {
        // Without the newline the whole statement would be one `--` comment.
        let out = declare_cursor("c", "-- note\nSELECT 1");
        assert!(out.contains("FOR\n-- note\nSELECT 1"), "{out}");
    }

    #[test]
    fn a_window_positions_absolutely_then_reads_forward() {
        assert_eq!(
            window_statements("picus_cur_2", 500, 201),
            "MOVE ABSOLUTE 500 FROM \"picus_cur_2\"; FETCH FORWARD 201 FROM \"picus_cur_2\""
        );
        // Offset 0 is the same statement, not a special case.
        assert_eq!(
            window_statements("c", 0, 10),
            "MOVE ABSOLUTE 0 FROM \"c\"; FETCH FORWARD 10 FROM \"c\""
        );
    }

    #[test]
    fn an_absurd_offset_is_clamped_rather_than_sent() {
        let out = window_statements("c", u64::MAX, 10);
        assert!(out.contains(&format!("MOVE ABSOLUTE {} FROM", i64::MAX)), "{out}");
    }

    #[test]
    fn counting_rewinds_then_walks() {
        assert_eq!(
            count_statements("c"),
            "MOVE ABSOLUTE 0 FROM \"c\"; MOVE FORWARD ALL FROM \"c\""
        );
    }

    #[test]
    fn a_hostile_cursor_name_cannot_escape_its_identifier() {
        // Names are generated, never received — but the quoting is what makes that
        // a defence in depth rather than a promise.
        let out = declare_cursor(r#"x"; DROP TABLE y; --"#, "SELECT 1");
        assert!(out.starts_with(r#"DECLARE "x""; DROP TABLE y; --" SCROLL"#), "{out}");
        assert!(close_statement(r#"a"b"#).starts_with(r#"CLOSE "a""b""#));
    }

    #[test]
    fn the_row_estimate_is_read_out_of_the_first_plan_line() {
        assert_eq!(
            plan_row_estimate("Seq Scan on orders  (cost=0.00..18.50 rows=850 width=36)"),
            Some(850)
        );
        assert_eq!(
            plan_row_estimate("Limit  (cost=0.00..0.04 rows=1 width=4)"),
            Some(1)
        );
        assert_eq!(plan_row_estimate("Result  (cost=0.00..0.01 width=4)"), None);
        assert_eq!(plan_row_estimate(""), None, "unknown, and it must not read as zero");
    }

    #[test]
    fn a_relation_is_quoted_and_qualified_by_the_engine() {
        assert_eq!(relation_query("public", "orders"), r#"SELECT * FROM "public"."orders""#);
        // Already qualified: honoured as written, not pinned to the session schema.
        assert_eq!(relation_query("public", "audit.log"), r#"SELECT * FROM "audit"."log""#);
        // Mixed case survives, which is the entire reason for quoting on PostgreSQL.
        assert_eq!(relation_query("public", "Orders"), r#"SELECT * FROM "public"."Orders""#);
        assert_eq!(
            relation_query("public", r#"x"; DROP TABLE y; --"#),
            r#"SELECT * FROM "public"."x""; DROP TABLE y; --""#
        );
    }

    #[test]
    fn a_relation_query_is_itself_cursorable() {
        // The relation tab and the query tab must end up on the same path, or the
        // product has two behaviours for one thing.
        let sql = relation_query("public", "orders");
        assert!(matches!(plan_execution(&sql), ExecutionPlan::Cursor(_)));
    }

    #[test]
    fn explain_does_not_run_the_query() {
        let out = explain_statement("SELECT 1");
        assert!(out.starts_with("EXPLAIN\n"), "{out}");
        assert!(!out.contains("ANALYZE"), "ANALYZE would execute it");
    }

    // ── Reading a window without materialising the rest ────────────────────────

    #[test]
    fn the_first_window_declares_and_closes_inside_one_round_trip() {
        let out = first_window_statements("picus_cur_7", "SELECT * FROM archivio", 501);
        assert_eq!(
            out,
            "BEGIN; DECLARE \"picus_cur_7\" NO SCROLL CURSOR FOR\nSELECT * FROM archivio\n; \
             FETCH FORWARD 501 FROM \"picus_cur_7\"; CLOSE \"picus_cur_7\"; COMMIT",
        );
        // The transaction closes in the same string it opened in. A `BEGIN` that
        // reached the server without its `COMMIT` would enclose every other tab's
        // statement on this connection.
        assert!(out.starts_with("BEGIN;") && out.ends_with("COMMIT"));
        // WITHOUT `HOLD` — that one word is the difference between fetching 501 rows
        // and materialising the table.
        assert!(!out.contains("HOLD"), "{out}");
    }

    #[test]
    fn the_body_reaches_the_declaration_unchanged() {
        // The whole reason this is a cursor and not `SELECT * FROM (<body>) LIMIT n`:
        // PostgreSQL does not promise to preserve a sub-select's ordering, and
        // handing back rows in another order is worse than a slow query.
        let body = "SELECT * FROM archivio WHERE stato = 'EV' ORDER BY protocollo DESC LIMIT 20";
        assert!(first_window_statements("c", body, 501).contains(body), "verbatim");
        // A `--` on the last line must not comment out the terminator after it.
        let commented = first_window_statements("c", "SELECT 1 -- ultima riga", 10);
        assert!(commented.contains("-- ultima riga\n;"), "{commented}");
    }

    #[test]
    fn the_bound_goes_into_the_statement_where_the_planner_can_see_it() {
        // The difference between a top-N sort and sorting the whole table to disk.
        assert_eq!(
            bounded_body("SELECT * FROM archivio ORDER BY protocollo", 501).as_deref(),
            Some("SELECT * FROM archivio ORDER BY protocollo\nLIMIT 501"),
        );
        // The newline is the comment case, again.
        assert!(bounded_body("SELECT 1 -- fine", 10).unwrap().contains("-- fine\nLIMIT 10"));
    }

    #[test]
    fn a_statement_that_bounds_itself_is_left_alone() {
        // Appending after any of these is a syntax error — and a statement that
        // already bounds itself does not need ours.
        for body in [
            "SELECT * FROM archivio LIMIT 20",
            "SELECT * FROM archivio OFFSET 10",
            "SELECT * FROM archivio FETCH FIRST 5 ROWS ONLY",
            "SELECT * FROM archivio FOR UPDATE",
        ] {
            assert_eq!(bounded_body(body, 501), None, "{body}");
        }
        // …but the same words *inside* a subquery bound that subquery, not this
        // statement.
        assert!(bounded_body("SELECT * FROM (SELECT 1 LIMIT 5) s", 501).is_some());
    }

    #[test]
    fn only_a_top_level_ordering_counts_as_one() {
        assert!(orders_its_own_rows("SELECT * FROM archivio ORDER BY protocollo"));
        assert!(orders_its_own_rows("select 1 order by 1"));
        // A window function orders inside its own parentheses, and a subquery
        // inside its own — neither is this statement's ordering, so neither stops
        // the masking.
        assert!(!orders_its_own_rows(
            "SELECT row_number() OVER (ORDER BY protocollo) FROM archivio"
        ));
        assert!(!orders_its_own_rows("SELECT * FROM (SELECT 1 ORDER BY 1) s"));
        // Nor does text that merely reads like one.
        assert!(!orders_its_own_rows("SELECT 'order by' FROM archivio"));
        assert!(!orders_its_own_rows(r#"SELECT "order by" FROM archivio"#));
        assert!(!orders_its_own_rows("SELECT 1 -- order by protocollo"));
        assert!(!orders_its_own_rows("SELECT $$ order by $$"));
    }

    #[test]
    fn two_first_windows_do_not_collide_on_a_name() {
        // A background count on one tab and a Run on another share one connection.
        // A fixed name here would make the second `DECLARE` fail — and a failure
        // inside that string leaves the whole connection in an aborted transaction.
        let a = first_window_statements("picus_cur_1", "SELECT 1", 10);
        let b = first_window_statements("picus_cur_2", "SELECT 1", 10);
        assert_ne!(a, b);
        assert!(a.contains("\"picus_cur_1\"") && !a.contains("picus_cur_2"));
    }

    #[test]
    fn masking_wraps_the_statement_rather_than_editing_its_projection() {
        // Wrapping is what makes it work for a join or a union without this module
        // understanding either.
        assert_eq!(
            masked_source(
                "SELECT protocollo, scansione FROM archivio",
                &[("protocollo".to_string(), false), ("scansione".to_string(), true)],
            ),
            "SELECT \"protocollo\", pg_column_size(\"scansione\") AS \"scansione\" \
             FROM (\nSELECT protocollo, scansione FROM archivio\n) AS picus_src",
        );
        assert!(masked_source("SELECT 1 -- fine", &[]).contains("-- fine\n)"));
    }

    #[test]
    fn an_undeclared_result_is_counted_without_reading_its_columns() {
        // `count(*)` needs none of the columns, so a table whose rows are megabytes
        // of `bytea` is counted without touching one of them.
        assert_eq!(
            count_query("SELECT * FROM archivio"),
            "SELECT count(*) FROM (\nSELECT * FROM archivio\n) AS picus_total",
        );
        assert!(count_query("SELECT 1 -- fine").contains("-- fine\n)"));
    }

    #[test]
    fn the_masked_projection_names_every_column_and_computes_only_the_heavy_ones() {
        let out = masked_projection(&[
            ("protocollo".to_string(), false),
            ("scansione".to_string(), true),
        ]);
        assert_eq!(out, r#""protocollo", pg_column_size("scansione") AS "scansione""#);
        // The alias matters: the grid, the export and the on-demand read all address
        // the column by its own name.
        assert!(out.contains(r#"AS "scansione""#));
    }

}
