/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 102
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 1
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_jsp_comment = 1,
  sym_jsp_directive = 2,
  sym_jsp_declaration = 3,
  sym_jsp_expression = 4,
  sym_jsp_scriptlet = 5,
  sym_html_comment = 6,
  sym_cdata = 7,
  sym_doctype = 8,
  sym_el_expression = 9,
  sym_ognl_expression = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LT_SLASH = 13,
  sym_script_tag = 14,
  sym_style_tag = 15,
  sym_raw_text = 16,
  anon_sym_SLASH_GT = 17,
  sym_tag_name = 18,
  anon_sym_EQ = 19,
  sym_attribute_name = 20,
  anon_sym_DQUOTE = 21,
  anon_sym_SQUOTE = 22,
  sym_attribute_fragment = 23,
  sym_attribute_fragment_sq = 24,
  sym_unquoted_value = 25,
  sym__ws = 26,
  sym_text = 27,
  sym_stray = 28,
  sym_document = 29,
  sym__node = 30,
  sym_script_element = 31,
  sym_style_element = 32,
  sym_start_tag = 33,
  sym_self_closing_tag = 34,
  sym_end_tag = 35,
  sym_attribute = 36,
  sym__attribute_value = 37,
  sym_quoted_value_double = 38,
  sym_quoted_value_single = 39,
  aux_sym_document_repeat1 = 40,
  aux_sym_script_element_repeat1 = 41,
  aux_sym_quoted_value_double_repeat1 = 42,
  aux_sym_quoted_value_single_repeat1 = 43,
  alias_sym_style_content = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_jsp_comment] = "jsp_comment",
  [sym_jsp_directive] = "jsp_directive",
  [sym_jsp_declaration] = "jsp_declaration",
  [sym_jsp_expression] = "jsp_expression",
  [sym_jsp_scriptlet] = "jsp_scriptlet",
  [sym_html_comment] = "html_comment",
  [sym_cdata] = "cdata",
  [sym_doctype] = "doctype",
  [sym_el_expression] = "el_expression",
  [sym_ognl_expression] = "ognl_expression",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [sym_script_tag] = "script_tag",
  [sym_style_tag] = "style_tag",
  [sym_raw_text] = "script_content",
  [anon_sym_SLASH_GT] = "/>",
  [sym_tag_name] = "tag_name",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [sym_attribute_fragment] = "attribute_fragment",
  [sym_attribute_fragment_sq] = "attribute_fragment_sq",
  [sym_unquoted_value] = "unquoted_value",
  [sym__ws] = "_ws",
  [sym_text] = "text",
  [sym_stray] = "stray",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_attribute] = "attribute",
  [sym__attribute_value] = "_attribute_value",
  [sym_quoted_value_double] = "quoted_value_double",
  [sym_quoted_value_single] = "quoted_value_single",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_script_element_repeat1] = "script_element_repeat1",
  [aux_sym_quoted_value_double_repeat1] = "quoted_value_double_repeat1",
  [aux_sym_quoted_value_single_repeat1] = "quoted_value_single_repeat1",
  [alias_sym_style_content] = "style_content",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_jsp_comment] = sym_jsp_comment,
  [sym_jsp_directive] = sym_jsp_directive,
  [sym_jsp_declaration] = sym_jsp_declaration,
  [sym_jsp_expression] = sym_jsp_expression,
  [sym_jsp_scriptlet] = sym_jsp_scriptlet,
  [sym_html_comment] = sym_html_comment,
  [sym_cdata] = sym_cdata,
  [sym_doctype] = sym_doctype,
  [sym_el_expression] = sym_el_expression,
  [sym_ognl_expression] = sym_ognl_expression,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [sym_script_tag] = sym_script_tag,
  [sym_style_tag] = sym_style_tag,
  [sym_raw_text] = sym_raw_text,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [sym_tag_name] = sym_tag_name,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_attribute_fragment] = sym_attribute_fragment,
  [sym_attribute_fragment_sq] = sym_attribute_fragment_sq,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym__ws] = sym__ws,
  [sym_text] = sym_text,
  [sym_stray] = sym_stray,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_attribute] = sym_attribute,
  [sym__attribute_value] = sym__attribute_value,
  [sym_quoted_value_double] = sym_quoted_value_double,
  [sym_quoted_value_single] = sym_quoted_value_single,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_script_element_repeat1] = aux_sym_script_element_repeat1,
  [aux_sym_quoted_value_double_repeat1] = aux_sym_quoted_value_double_repeat1,
  [aux_sym_quoted_value_single_repeat1] = aux_sym_quoted_value_single_repeat1,
  [alias_sym_style_content] = alias_sym_style_content,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_jsp_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_jsp_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_jsp_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_jsp_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_jsp_scriptlet] = {
    .visible = true,
    .named = true,
  },
  [sym_html_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_cdata] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_el_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_ognl_expression] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_script_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_fragment] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_fragment_sq] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_stray] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_quoted_value_double] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_value_single] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_script_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_value_double_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_value_single_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_style_content] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [3] = alias_sym_style_content,
  },
  [2] = {
    [4] = alias_sym_style_content,
  },
  [3] = {
    [5] = alias_sym_style_content,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(63);
      ADVANCE_MAP(
        '"', 107,
        '#', 114,
        '$', 114,
        '%', 115,
        '\'', 108,
        '<', 77,
        '=', 104,
        '>', 78,
        'S', 84,
        's', 84,
        ':', 106,
        '@', 106,
        '_', 106,
        '\t', 112,
        '\n', 112,
        '\r', 112,
        ' ', 112,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      if (lookahead != 0) ADVANCE(113);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(7);
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead == '=') ADVANCE(10);
      if (lookahead == '@') ADVANCE(11);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(107);
      if (lookahead == '#') ADVANCE(48);
      if (lookahead == '$') ADVANCE(48);
      if (lookahead == '%') ADVANCE(50);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(107);
      if (lookahead == '\'') ADVANCE(108);
      if (lookahead == '>') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(111);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(49);
      if (lookahead == '$') ADVANCE(49);
      if (lookahead == '%') ADVANCE(51);
      if (lookahead == '\'') ADVANCE(108);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 5:
      if (lookahead == '%') ADVANCE(33);
      if (lookahead == '-') ADVANCE(9);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '%') ADVANCE(33);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '%') ADVANCE(34);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '-') ADVANCE(12);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '%') ADVANCE(19);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '%') ADVANCE(35);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '%') ADVANCE(36);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '%') ADVANCE(39);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == '%') ADVANCE(40);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == '[') ADVANCE(28);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == '-') ADVANCE(22);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '>') ADVANCE(72);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 17:
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '>') ADVANCE(73);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == '-') ADVANCE(13);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '>') ADVANCE(69);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == '-') ADVANCE(18);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '>') ADVANCE(73);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == '-') ADVANCE(38);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == '/') ADVANCE(79);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 24:
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == '=') ADVANCE(104);
      if (lookahead == '>') ADVANCE(78);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead == ':' ||
          ('@' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 25:
      if (lookahead == '<') ADVANCE(23);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 26:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == 'A') ADVANCE(30);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 27:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == 'A') ADVANCE(31);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == 'C') ADVANCE(29);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 29:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == 'D') ADVANCE(26);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == 'T') ADVANCE(27);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead == '[') ADVANCE(41);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 32:
      if (lookahead == '>') ADVANCE(72);
      if (lookahead != 0) ADVANCE(32);
      END_STATE();
    case 33:
      if (lookahead == '>') ADVANCE(68);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 34:
      if (lookahead == '>') ADVANCE(66);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 35:
      if (lookahead == '>') ADVANCE(67);
      if (lookahead != 0) ADVANCE(10);
      END_STATE();
    case 36:
      if (lookahead == '>') ADVANCE(65);
      if (lookahead != 0) ADVANCE(11);
      END_STATE();
    case 37:
      if (lookahead == '>') ADVANCE(70);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 38:
      if (lookahead == '>') ADVANCE(70);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 39:
      if (lookahead == '>') ADVANCE(64);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 40:
      if (lookahead == '>') ADVANCE(64);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 41:
      if (lookahead == '>') ADVANCE(74);
      if (lookahead == ']') ADVANCE(42);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 42:
      if (lookahead == '>') ADVANCE(74);
      if (lookahead == ']') ADVANCE(43);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 43:
      if (lookahead == '>') ADVANCE(71);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 44:
      if (lookahead == '>') ADVANCE(71);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 45:
      if (lookahead == '>') ADVANCE(83);
      END_STATE();
    case 46:
      if (lookahead == ']') ADVANCE(47);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 47:
      if (lookahead == ']') ADVANCE(44);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 48:
      if (lookahead == '{') ADVANCE(52);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 49:
      if (lookahead == '{') ADVANCE(52);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 50:
      if (lookahead == '{') ADVANCE(53);
      if (lookahead != 0) ADVANCE(109);
      END_STATE();
    case 51:
      if (lookahead == '{') ADVANCE(53);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 52:
      if (lookahead == '}') ADVANCE(75);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 53:
      if (lookahead == '}') ADVANCE(76);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 54:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(93);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 55:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 56:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 57:
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '%' &&
          lookahead != '/' &&
          (lookahead < 'A' || 'Z' < lookahead) &&
          (lookahead < 'a' || 'z' < lookahead)) ADVANCE(113);
      END_STATE();
    case 58:
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '{') ADVANCE(113);
      END_STATE();
    case 59:
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(82);
      END_STATE();
    case 60:
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(109);
      END_STATE();
    case 61:
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(110);
      END_STATE();
    case 62:
      if (eof) ADVANCE(63);
      if (lookahead == '#') ADVANCE(114);
      if (lookahead == '$') ADVANCE(114);
      if (lookahead == '%') ADVANCE(115);
      if (lookahead == '<') ADVANCE(77);
      if (lookahead != 0) ADVANCE(113);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_jsp_comment);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_jsp_directive);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_jsp_declaration);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_jsp_expression);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_jsp_scriptlet);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_jsp_scriptlet);
      if (lookahead == '-') ADVANCE(18);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_html_comment);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_cdata);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_doctype);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_doctype);
      if (lookahead == '-') ADVANCE(22);
      if (lookahead != 0) ADVANCE(15);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_doctype);
      if (lookahead == ']') ADVANCE(47);
      if (lookahead != 0) ADVANCE(46);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_el_expression);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_ognl_expression);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(14);
      if (lookahead == '%') ADVANCE(1);
      if (lookahead == '/') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_script_tag);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_style_tag);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_raw_text);
      if (lookahead == '<') ADVANCE(59);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(89);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(91);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(81);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(88);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(85);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(90);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(86);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(80);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(87);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(105);
      if (lookahead == '_') ADVANCE(106);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(98);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(100);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(81);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(97);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(94);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(99);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(95);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(80);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(96);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == ':' ||
          lookahead == '_') ADVANCE(106);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          lookahead == '_') ADVANCE(106);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_attribute_fragment);
      if (lookahead == '#') ADVANCE(60);
      if (lookahead == '$') ADVANCE(60);
      if (lookahead == '%') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '"' || '%' < lookahead)) ADVANCE(109);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_attribute_fragment_sq);
      if (lookahead == '#') ADVANCE(61);
      if (lookahead == '$') ADVANCE(61);
      if (lookahead == '%') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(110);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '>') ADVANCE(111);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(112);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(58);
      if (lookahead == '$') ADVANCE(58);
      if (lookahead == '%') ADVANCE(58);
      if (lookahead == '<') ADVANCE(57);
      if (lookahead != 0) ADVANCE(113);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(113);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(113);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 62},
  [2] = {.lex_state = 62},
  [3] = {.lex_state = 62},
  [4] = {.lex_state = 62},
  [5] = {.lex_state = 62},
  [6] = {.lex_state = 62},
  [7] = {.lex_state = 62},
  [8] = {.lex_state = 62},
  [9] = {.lex_state = 62},
  [10] = {.lex_state = 62},
  [11] = {.lex_state = 62},
  [12] = {.lex_state = 62},
  [13] = {.lex_state = 62},
  [14] = {.lex_state = 62},
  [15] = {.lex_state = 62},
  [16] = {.lex_state = 62},
  [17] = {.lex_state = 62},
  [18] = {.lex_state = 62},
  [19] = {.lex_state = 62},
  [20] = {.lex_state = 62},
  [21] = {.lex_state = 62},
  [22] = {.lex_state = 62},
  [23] = {.lex_state = 62},
  [24] = {.lex_state = 62},
  [25] = {.lex_state = 62},
  [26] = {.lex_state = 62},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 24},
  [35] = {.lex_state = 24},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 24},
  [38] = {.lex_state = 24},
  [39] = {.lex_state = 24},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 54},
  [43] = {.lex_state = 24},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 24},
  [46] = {.lex_state = 24},
  [47] = {.lex_state = 24},
  [48] = {.lex_state = 24},
  [49] = {.lex_state = 24},
  [50] = {.lex_state = 24},
  [51] = {.lex_state = 24},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 24},
  [54] = {.lex_state = 24},
  [55] = {.lex_state = 25},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 25},
  [61] = {.lex_state = 25},
  [62] = {.lex_state = 25},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 25},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 25},
  [71] = {.lex_state = 24},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 54},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 54},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 54},
  [81] = {.lex_state = 55},
  [82] = {.lex_state = 3},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 54},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 3},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 3},
  [90] = {.lex_state = 54},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 54},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 54},
  [97] = {.lex_state = 54},
  [98] = {.lex_state = 54},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 54},
  [101] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_jsp_comment] = ACTIONS(1),
    [sym_jsp_directive] = ACTIONS(1),
    [sym_jsp_declaration] = ACTIONS(1),
    [sym_jsp_expression] = ACTIONS(1),
    [sym_jsp_scriptlet] = ACTIONS(1),
    [sym_html_comment] = ACTIONS(1),
    [sym_cdata] = ACTIONS(1),
    [sym_doctype] = ACTIONS(1),
    [sym_el_expression] = ACTIONS(1),
    [sym_ognl_expression] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [sym_script_tag] = ACTIONS(1),
    [sym_style_tag] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_attribute_name] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_stray] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(83),
    [sym__node] = STATE(2),
    [sym_script_element] = STATE(2),
    [sym_style_element] = STATE(2),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(2),
    [sym_end_tag] = STATE(2),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_jsp_comment] = ACTIONS(5),
    [sym_jsp_directive] = ACTIONS(5),
    [sym_jsp_declaration] = ACTIONS(5),
    [sym_jsp_expression] = ACTIONS(5),
    [sym_jsp_scriptlet] = ACTIONS(7),
    [sym_html_comment] = ACTIONS(5),
    [sym_cdata] = ACTIONS(5),
    [sym_doctype] = ACTIONS(7),
    [sym_el_expression] = ACTIONS(5),
    [sym_ognl_expression] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_text] = ACTIONS(7),
    [sym_stray] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 4,
      sym_jsp_scriptlet,
      sym_doctype,
      sym_text,
      sym_stray,
    STATE(3), 7,
      sym__node,
      sym_script_element,
      sym_style_element,
      sym_start_tag,
      sym_self_closing_tag,
      sym_end_tag,
      aux_sym_document_repeat1,
    ACTIONS(15), 8,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
  [35] = 6,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_LT,
    ACTIONS(30), 1,
      anon_sym_LT_SLASH,
    ACTIONS(24), 4,
      sym_jsp_scriptlet,
      sym_doctype,
      sym_text,
      sym_stray,
    STATE(3), 7,
      sym__node,
      sym_script_element,
      sym_style_element,
      sym_start_tag,
      sym_self_closing_tag,
      sym_end_tag,
      aux_sym_document_repeat1,
    ACTIONS(21), 8,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
  [70] = 2,
    ACTIONS(35), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(33), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [90] = 2,
    ACTIONS(39), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(37), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [110] = 2,
    ACTIONS(43), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(41), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [130] = 2,
    ACTIONS(47), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(45), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [150] = 2,
    ACTIONS(51), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(49), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [170] = 2,
    ACTIONS(55), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(53), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [190] = 2,
    ACTIONS(59), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(57), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [210] = 2,
    ACTIONS(63), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(61), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [230] = 2,
    ACTIONS(67), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(65), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [250] = 2,
    ACTIONS(71), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(69), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [270] = 2,
    ACTIONS(75), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(73), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [290] = 2,
    ACTIONS(79), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(77), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [310] = 2,
    ACTIONS(83), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(81), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [330] = 2,
    ACTIONS(87), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(85), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [350] = 2,
    ACTIONS(91), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(89), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [370] = 2,
    ACTIONS(95), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(93), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [390] = 2,
    ACTIONS(99), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(97), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [410] = 2,
    ACTIONS(103), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(101), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [430] = 2,
    ACTIONS(107), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(105), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [450] = 2,
    ACTIONS(111), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(109), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [470] = 2,
    ACTIONS(115), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(113), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [490] = 2,
    ACTIONS(119), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(117), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [510] = 2,
    ACTIONS(123), 5,
      sym_jsp_scriptlet,
      sym_doctype,
      anon_sym_LT,
      sym_text,
      sym_stray,
    ACTIONS(121), 10,
      ts_builtin_sym_end,
      sym_jsp_comment,
      sym_jsp_directive,
      sym_jsp_declaration,
      sym_jsp_expression,
      sym_html_comment,
      sym_cdata,
      sym_el_expression,
      sym_ognl_expression,
      anon_sym_LT_SLASH,
  [530] = 4,
    ACTIONS(125), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      anon_sym_SQUOTE,
    ACTIONS(129), 1,
      sym_unquoted_value,
    STATE(43), 3,
      sym__attribute_value,
      sym_quoted_value_double,
      sym_quoted_value_single,
  [545] = 3,
    ACTIONS(133), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      aux_sym_quoted_value_double_repeat1,
    ACTIONS(131), 3,
      sym_el_expression,
      sym_ognl_expression,
      sym_attribute_fragment,
  [557] = 3,
    ACTIONS(138), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      aux_sym_quoted_value_double_repeat1,
    ACTIONS(135), 3,
      sym_el_expression,
      sym_ognl_expression,
      sym_attribute_fragment,
  [569] = 3,
    ACTIONS(143), 1,
      anon_sym_SQUOTE,
    STATE(30), 1,
      aux_sym_quoted_value_single_repeat1,
    ACTIONS(140), 3,
      sym_el_expression,
      sym_ognl_expression,
      sym_attribute_fragment_sq,
  [581] = 3,
    ACTIONS(147), 1,
      anon_sym_SQUOTE,
    STATE(30), 1,
      aux_sym_quoted_value_single_repeat1,
    ACTIONS(145), 3,
      sym_el_expression,
      sym_ognl_expression,
      sym_attribute_fragment_sq,
  [593] = 3,
    ACTIONS(151), 1,
      anon_sym_DQUOTE,
    STATE(28), 1,
      aux_sym_quoted_value_double_repeat1,
    ACTIONS(149), 3,
      sym_el_expression,
      sym_ognl_expression,
      sym_attribute_fragment,
  [605] = 3,
    ACTIONS(155), 1,
      anon_sym_SQUOTE,
    STATE(31), 1,
      aux_sym_quoted_value_single_repeat1,
    ACTIONS(153), 3,
      sym_el_expression,
      sym_ognl_expression,
      sym_attribute_fragment_sq,
  [617] = 4,
    ACTIONS(157), 1,
      anon_sym_GT,
    ACTIONS(159), 1,
      anon_sym_SLASH_GT,
    ACTIONS(161), 1,
      sym_attribute_name,
    STATE(46), 1,
      sym_attribute,
  [630] = 4,
    ACTIONS(163), 1,
      anon_sym_GT,
    ACTIONS(165), 1,
      anon_sym_SLASH_GT,
    ACTIONS(167), 1,
      sym__ws,
    STATE(37), 1,
      aux_sym_script_element_repeat1,
  [643] = 2,
    ACTIONS(171), 1,
      anon_sym_EQ,
    ACTIONS(169), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [652] = 4,
    ACTIONS(173), 1,
      anon_sym_GT,
    ACTIONS(175), 1,
      anon_sym_SLASH_GT,
    ACTIONS(177), 1,
      sym__ws,
    STATE(39), 1,
      aux_sym_script_element_repeat1,
  [665] = 4,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(173), 1,
      anon_sym_GT,
    ACTIONS(175), 1,
      anon_sym_SLASH_GT,
    STATE(46), 1,
      sym_attribute,
  [678] = 3,
    ACTIONS(181), 1,
      sym__ws,
    STATE(39), 1,
      aux_sym_script_element_repeat1,
    ACTIONS(179), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [689] = 3,
    ACTIONS(184), 1,
      anon_sym_GT,
    ACTIONS(186), 1,
      sym__ws,
    STATE(41), 1,
      aux_sym_script_element_repeat1,
  [699] = 3,
    ACTIONS(188), 1,
      anon_sym_GT,
    ACTIONS(190), 1,
      sym__ws,
    STATE(39), 1,
      aux_sym_script_element_repeat1,
  [709] = 3,
    ACTIONS(192), 1,
      sym_script_tag,
    ACTIONS(194), 1,
      sym_style_tag,
    ACTIONS(196), 1,
      sym_tag_name,
  [719] = 1,
    ACTIONS(198), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [725] = 3,
    ACTIONS(200), 1,
      anon_sym_GT,
    ACTIONS(202), 1,
      sym__ws,
    STATE(52), 1,
      aux_sym_script_element_repeat1,
  [735] = 1,
    ACTIONS(204), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [741] = 1,
    ACTIONS(179), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [747] = 3,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(206), 1,
      anon_sym_GT,
    STATE(46), 1,
      sym_attribute,
  [757] = 3,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(208), 1,
      anon_sym_GT,
    STATE(46), 1,
      sym_attribute,
  [767] = 1,
    ACTIONS(210), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [773] = 1,
    ACTIONS(212), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [779] = 3,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(214), 1,
      anon_sym_GT,
    STATE(46), 1,
      sym_attribute,
  [789] = 3,
    ACTIONS(208), 1,
      anon_sym_GT,
    ACTIONS(216), 1,
      sym__ws,
    STATE(39), 1,
      aux_sym_script_element_repeat1,
  [799] = 3,
    ACTIONS(161), 1,
      sym_attribute_name,
    ACTIONS(188), 1,
      anon_sym_GT,
    STATE(46), 1,
      sym_attribute,
  [809] = 1,
    ACTIONS(218), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym__ws,
  [815] = 2,
    ACTIONS(220), 1,
      anon_sym_LT_SLASH,
    ACTIONS(222), 1,
      sym_raw_text,
  [822] = 2,
    ACTIONS(224), 1,
      anon_sym_GT,
    ACTIONS(226), 1,
      sym__ws,
  [829] = 2,
    ACTIONS(228), 1,
      anon_sym_GT,
    ACTIONS(230), 1,
      sym__ws,
  [836] = 2,
    ACTIONS(232), 1,
      anon_sym_GT,
    ACTIONS(234), 1,
      sym__ws,
  [843] = 2,
    ACTIONS(236), 1,
      anon_sym_GT,
    ACTIONS(238), 1,
      sym__ws,
  [850] = 2,
    ACTIONS(240), 1,
      anon_sym_LT_SLASH,
    ACTIONS(242), 1,
      sym_raw_text,
  [857] = 2,
    ACTIONS(244), 1,
      anon_sym_LT_SLASH,
    ACTIONS(246), 1,
      sym_raw_text,
  [864] = 2,
    ACTIONS(248), 1,
      anon_sym_LT_SLASH,
    ACTIONS(250), 1,
      sym_raw_text,
  [871] = 2,
    ACTIONS(252), 1,
      anon_sym_GT,
    ACTIONS(254), 1,
      sym__ws,
  [878] = 2,
    ACTIONS(256), 1,
      anon_sym_GT,
    ACTIONS(258), 1,
      sym__ws,
  [885] = 2,
    ACTIONS(260), 1,
      anon_sym_GT,
    ACTIONS(262), 1,
      sym__ws,
  [892] = 2,
    ACTIONS(264), 1,
      anon_sym_GT,
    ACTIONS(266), 1,
      sym__ws,
  [899] = 2,
    ACTIONS(268), 1,
      anon_sym_LT_SLASH,
    ACTIONS(270), 1,
      sym_raw_text,
  [906] = 2,
    ACTIONS(272), 1,
      anon_sym_GT,
    ACTIONS(274), 1,
      sym__ws,
  [913] = 2,
    ACTIONS(276), 1,
      anon_sym_GT,
    ACTIONS(278), 1,
      sym__ws,
  [920] = 2,
    ACTIONS(280), 1,
      anon_sym_LT_SLASH,
    ACTIONS(282), 1,
      sym_raw_text,
  [927] = 2,
    ACTIONS(161), 1,
      sym_attribute_name,
    STATE(46), 1,
      sym_attribute,
  [934] = 2,
    ACTIONS(284), 1,
      anon_sym_GT,
    ACTIONS(286), 1,
      sym__ws,
  [941] = 1,
    ACTIONS(288), 1,
      anon_sym_GT,
  [945] = 1,
    ACTIONS(290), 1,
      anon_sym_LT_SLASH,
  [949] = 1,
    ACTIONS(292), 1,
      sym_style_tag,
  [953] = 1,
    ACTIONS(294), 1,
      anon_sym_GT,
  [957] = 1,
    ACTIONS(256), 1,
      anon_sym_GT,
  [961] = 1,
    ACTIONS(296), 1,
      sym_style_tag,
  [965] = 1,
    ACTIONS(298), 1,
      anon_sym_LT_SLASH,
  [969] = 1,
    ACTIONS(300), 1,
      sym_style_tag,
  [973] = 1,
    ACTIONS(302), 1,
      sym_tag_name,
  [977] = 1,
    ACTIONS(264), 1,
      anon_sym_GT,
  [981] = 1,
    ACTIONS(304), 1,
      ts_builtin_sym_end,
  [985] = 1,
    ACTIONS(306), 1,
      sym_style_tag,
  [989] = 1,
    ACTIONS(240), 1,
      anon_sym_LT_SLASH,
  [993] = 1,
    ACTIONS(308), 1,
      anon_sym_LT_SLASH,
  [997] = 1,
    ACTIONS(236), 1,
      anon_sym_GT,
  [1001] = 1,
    ACTIONS(232), 1,
      anon_sym_GT,
  [1005] = 1,
    ACTIONS(272), 1,
      anon_sym_GT,
  [1009] = 1,
    ACTIONS(310), 1,
      sym_style_tag,
  [1013] = 1,
    ACTIONS(312), 1,
      anon_sym_GT,
  [1017] = 1,
    ACTIONS(314), 1,
      anon_sym_GT,
  [1021] = 1,
    ACTIONS(316), 1,
      anon_sym_LT_SLASH,
  [1025] = 1,
    ACTIONS(318), 1,
      sym_style_tag,
  [1029] = 1,
    ACTIONS(320), 1,
      anon_sym_GT,
  [1033] = 1,
    ACTIONS(322), 1,
      sym_script_tag,
  [1037] = 1,
    ACTIONS(324), 1,
      sym_script_tag,
  [1041] = 1,
    ACTIONS(326), 1,
      sym_script_tag,
  [1045] = 1,
    ACTIONS(328), 1,
      anon_sym_GT,
  [1049] = 1,
    ACTIONS(330), 1,
      sym_script_tag,
  [1053] = 1,
    ACTIONS(248), 1,
      anon_sym_LT_SLASH,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 110,
  [SMALL_STATE(7)] = 130,
  [SMALL_STATE(8)] = 150,
  [SMALL_STATE(9)] = 170,
  [SMALL_STATE(10)] = 190,
  [SMALL_STATE(11)] = 210,
  [SMALL_STATE(12)] = 230,
  [SMALL_STATE(13)] = 250,
  [SMALL_STATE(14)] = 270,
  [SMALL_STATE(15)] = 290,
  [SMALL_STATE(16)] = 310,
  [SMALL_STATE(17)] = 330,
  [SMALL_STATE(18)] = 350,
  [SMALL_STATE(19)] = 370,
  [SMALL_STATE(20)] = 390,
  [SMALL_STATE(21)] = 410,
  [SMALL_STATE(22)] = 430,
  [SMALL_STATE(23)] = 450,
  [SMALL_STATE(24)] = 470,
  [SMALL_STATE(25)] = 490,
  [SMALL_STATE(26)] = 510,
  [SMALL_STATE(27)] = 530,
  [SMALL_STATE(28)] = 545,
  [SMALL_STATE(29)] = 557,
  [SMALL_STATE(30)] = 569,
  [SMALL_STATE(31)] = 581,
  [SMALL_STATE(32)] = 593,
  [SMALL_STATE(33)] = 605,
  [SMALL_STATE(34)] = 617,
  [SMALL_STATE(35)] = 630,
  [SMALL_STATE(36)] = 643,
  [SMALL_STATE(37)] = 652,
  [SMALL_STATE(38)] = 665,
  [SMALL_STATE(39)] = 678,
  [SMALL_STATE(40)] = 689,
  [SMALL_STATE(41)] = 699,
  [SMALL_STATE(42)] = 709,
  [SMALL_STATE(43)] = 719,
  [SMALL_STATE(44)] = 725,
  [SMALL_STATE(45)] = 735,
  [SMALL_STATE(46)] = 741,
  [SMALL_STATE(47)] = 747,
  [SMALL_STATE(48)] = 757,
  [SMALL_STATE(49)] = 767,
  [SMALL_STATE(50)] = 773,
  [SMALL_STATE(51)] = 779,
  [SMALL_STATE(52)] = 789,
  [SMALL_STATE(53)] = 799,
  [SMALL_STATE(54)] = 809,
  [SMALL_STATE(55)] = 815,
  [SMALL_STATE(56)] = 822,
  [SMALL_STATE(57)] = 829,
  [SMALL_STATE(58)] = 836,
  [SMALL_STATE(59)] = 843,
  [SMALL_STATE(60)] = 850,
  [SMALL_STATE(61)] = 857,
  [SMALL_STATE(62)] = 864,
  [SMALL_STATE(63)] = 871,
  [SMALL_STATE(64)] = 878,
  [SMALL_STATE(65)] = 885,
  [SMALL_STATE(66)] = 892,
  [SMALL_STATE(67)] = 899,
  [SMALL_STATE(68)] = 906,
  [SMALL_STATE(69)] = 913,
  [SMALL_STATE(70)] = 920,
  [SMALL_STATE(71)] = 927,
  [SMALL_STATE(72)] = 934,
  [SMALL_STATE(73)] = 941,
  [SMALL_STATE(74)] = 945,
  [SMALL_STATE(75)] = 949,
  [SMALL_STATE(76)] = 953,
  [SMALL_STATE(77)] = 957,
  [SMALL_STATE(78)] = 961,
  [SMALL_STATE(79)] = 965,
  [SMALL_STATE(80)] = 969,
  [SMALL_STATE(81)] = 973,
  [SMALL_STATE(82)] = 977,
  [SMALL_STATE(83)] = 981,
  [SMALL_STATE(84)] = 985,
  [SMALL_STATE(85)] = 989,
  [SMALL_STATE(86)] = 993,
  [SMALL_STATE(87)] = 997,
  [SMALL_STATE(88)] = 1001,
  [SMALL_STATE(89)] = 1005,
  [SMALL_STATE(90)] = 1009,
  [SMALL_STATE(91)] = 1013,
  [SMALL_STATE(92)] = 1017,
  [SMALL_STATE(93)] = 1021,
  [SMALL_STATE(94)] = 1025,
  [SMALL_STATE(95)] = 1029,
  [SMALL_STATE(96)] = 1033,
  [SMALL_STATE(97)] = 1037,
  [SMALL_STATE(98)] = 1041,
  [SMALL_STATE(99)] = 1045,
  [SMALL_STATE(100)] = 1049,
  [SMALL_STATE(101)] = 1053,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(81),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 9, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 9, 0, 2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 4, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 5, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 5, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 5, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 5, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 6, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 6, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 6, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 6, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 7, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 7, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 7, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 7, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 7, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 7, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 8, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 8, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 8, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 8, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 8, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 8, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 8, 0, 2),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 8, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 9, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 9, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 9, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 9, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 9, 0, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 9, 0, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 10, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 10, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 10, 0, 3),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 10, 0, 3),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_value_double_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_value_double_repeat1, 2, 0, 0),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_value_single_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quoted_value_single_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_script_element_repeat1, 2, 0, 0),
  [181] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_script_element_repeat1, 2, 0, 0), SHIFT_REPEAT(71),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_value_single, 2, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_value_double, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_value_single, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_value_double, 2, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [304] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_jsp(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "jsp",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
