//! `bennu-mapstruct` — MapStruct mappers, read the way the annotation processor reads them.
//!
//! ## Why an editor should know this
//!
//! A MapStruct mapper is an interface full of methods nobody writes. What they do is decided at
//! build time by the processor, and every mistake in one surfaces as a compiler message about
//! generated code, on the next build, often in a module somebody else is building:
//!
//! - `@Mapping(target = "nmae")` — a property that does not exist. The build fails.
//! - a target property nothing maps. The build **passes**, with a warning in a log nobody reads, and
//!   the field arrives `null` in production.
//! - `source` and `constant` on one `@Mapping`. The build fails.
//!
//! All three are answerable from the sources, in the file where they were written, while the
//! mapping is being typed. That is the crate.
//!
//! ## The bar
//!
//! A check here speaks only about types it can see **completely**: a project class whose whole
//! supertype chain is in the project, whose accessors are not generated by anything this crate cannot
//! read (a Lombok `@Accessors`, a hand-written builder, a composed mapping annotation), under a
//! reporting policy it could actually read. Anything else is silence — a type from a jar is not a
//! type with no properties, it is a type this crate knows nothing about.

// Reading the MapStruct annotations off a method's syntax tree.
pub mod annotations;
// The Mappers panel.
pub mod catalog;
// The diagnostics, derived from an analysed mapper.
pub mod checks;
// Completion, go-to and hover inside a `target` / `source` string.
pub mod editor;
// The extension itself — what a host registers.
pub mod ext;
// The Alt+Enter fixes.
pub mod fixes;
// Mappers and their mapping methods, analysed against the project.
pub mod mapper;
// The project model built on reindex.
pub mod model;
// Dotted property paths and the walk along them.
pub mod paths;
pub mod prelude;
// A type's MapStruct-visible properties, Lombok included.
pub mod properties;
// The project type table and name resolution.
pub mod table;

#[cfg(test)]
mod tests;
