//! Compiles the committed Tree-sitter parser (`src/parser.c`, generated by the dev-time
//! `tree-sitter generate`) via the `cc` build dependency. There is no external scanner —
//! the grammar is deliberately scanner-free (see `README.md` → "Design"), so this is one
//! file and nothing else.
//!
//! Same arrangement as `picus-parse` and `merula-lang`: `cargo build` needs a C compiler
//! and neither Node nor the Tree-sitter CLI.

use std::path::Path;

fn main() {
    let src = Path::new("src");

    let mut build = cc::Build::new();
    build.include(src);
    build.file(src.join("parser.c"));
    // The generated parser triggers warnings we do not own.
    build.warnings(false);
    build.flag_if_supported("-Wno-unused-parameter");
    build.flag_if_supported("-Wno-unused-but-set-variable");
    build.compile("tree-sitter-jsp");

    println!("cargo:rerun-if-changed=src/parser.c");
    println!("cargo:rerun-if-changed=src/tree_sitter/parser.h");
}
